### ISSUE TITLE
Race condition in FilesystemStore

### ISSUE THREAD

**Issue by cless** [gorilla/sessions#10]
There is a race condition in `FilesystemStore` that I intend to fix but I would like your input before I go ahead and do it. Basically the problem is that if you have concurrent requests from the same user (same session) that the following is possible:
1. Request 1 opens the session to perform a semi long operation
2. Request 2 opens the session
3. Request 2 Removes session data to perform "logout" or similar
4. Request 2 saves
5. Request 1 saves, which makes it as if the session was never logged out

I have added a test case for this flaw at cless/sessions@f84abeda17de0b4fcd72d277412f3d3192f206f2

The most straight forward way to fix this would be by introducing locks at the file system level. However, golang has no cross platform way to do file locking. It does expose `flock` in `syscall` but that only works if the OS supports it. I believe the behavior of flock might also be different on different unixes although I am not sure that this is the case. Another issue with flock is that it might not work on NFS.

An entirely different solution would be to keep a map of locks in the `FilesystemStore` object itself. This has another set of disadvantages: You can't have multiple processes access the same file system sessions and you can't create multiple stores for the same file system session within a single application. However, both these things are already impossible to do without causing issues.

In the end, I think the best solution is to keep a map of locks in the store object because all the disadvantages in that scenario can be properly documented and you can reply on the behavior being the same across different systems.

Other storage backends that are based on FilesystemStore might copy this flaw (I noticed this issue when reviewing Redistore code for a project of mine boj/redistore#2)

**Comment by mevdschee** [comment]
I agree totally with @cless and want to stress the importance of session locking and mature platforms (such as PHP) implement it on their session stores. On files it using flock and in memcache using the return value of the 'add' operation and an extra key with a '.lock' suffix and an expire set. I also agree with the approach of @kisielk to have a new interface (having the functions 'GetAndLock' and 'SaveAndRelease' makes sense. Can we have this please? Go should be the language to go to for high performance and reliability. I am willing to contribute some implementations (FileSystem, Redis and Memcache) for instance.

**Comment by HarikrishnanBalagopal** [comment]
What is the situation on this?
