### ISSUE TITLE
Artificially writing a cookie into a request and then reading for a test

### ISSUE THREAD

**Issue by dsoprea** [gorilla/sessions#100]
I'm having issues simulating the lifecycle of an incoming request (from `sessions_test.go`). I'm trying to add a unit-test for a PR.

The process:
1. Create fake request.
2. Creating a cookie with a session-ID.
3. Adding cookie to the request.
4. Reading ID back from cookie using proper flow.

I keep getting a "securecookie: the value is not valid" when I do the `Get` on the store. Can you clarify why?

```
# Added imports:
#
# os
# io/ioutil
# github.com/gorilla/securecookie
#

func TestSessionIdWriteAndRead(t *testing.T) {
    dir, err := ioutil.TempDir("", "accessor-write-test")
    if err != nil {
        t.Fatalf("Could not create temporary directory: %s", err)
    }

    defer os.RemoveAll(dir)

    // Stage the cookie payload to set (some encrypted string).

    sc := securecookie.New([]byte("12345"), []byte("1234567890123456"))
    value := "test_payload"
    encodedId, err := sc.Encode("sid", value)
    if err != nil {
        t.Fatalf("Could not encode test staging value: %s", err)
    }

    // Create cookie.

    name := "TestSession"

    so := &Options{
        Path: "/",
    }

    c := NewCookie(name, encodedId, so)

    // Create test request and set the cookie on it.
    req, _ := http.NewRequest("GET", "http://some.domain:8080/", nil)
    req.AddCookie(c)

    // Create session that should be backed by the cookie we just set.
    store := NewFilesystemStore(dir, []byte("12345"))
    session, err := store.Get(req, name)
    if err != nil {
        t.Fatalf("Error getting session: %v", err)
    }

    session = session
}
```

Thanks.

**Comment by elithrar** [comment]
This is how I test in gorilla/csrf -
https://github.com/gorilla/csrf/blob/master/store_test.go#L83-L97

**Comment by dsoprea** [comment]
It looks like that test is creating an intentionally bad value and setting it into a project-specific struct and executing that project's flow against it in the context of a response to induce an error. I'm not sure if that helps. Is there a test that encodes a value and correctly places it into a request? That's what I'm struggling with. Thanks, Matt. I appreciate the attention.

**Comment by elithrar** [comment]
What's not clear is what you're testing - you dip down to securecookie, but your main goal should just be to test what you get from *sessions* is what you put into it.

You are also providing both auth and encryption keys to securecookie, but only an auth key to NewFileSystemStore.

**Comment by dsoprea** [comment]
I wanted to write a cookie with a known ID stored in it, read it back, and assert that they're equal.

I'm not clear what the authentication key is for? Scrambling the ID versus the actual session data?

**Comment by elithrar** [comment]
The authentication key is for the HMAC - that is, to verify that the
content of the cookie has not been modified (useful), vs. encrypting it
(less useful in most cases).

I'll write you an email test tonight, but the way I typically write this:

- Create a test handler with a store.Get + session.Values + session.Save(w,
r) inside and save the content of the Set-Cookie header (don't touch
securecookie - just use sessions directly)
- Capture it via something like
https://github.com/gorilla/csrf/blob/master/csrf_test.go#L318-L320
- Create a new request against a test handler, and use store.Get +
session.Value to check that the id is the same as you saved above.

**Comment by dsoprea** [comment]
I'd rather you not waste substantial time on this. My original requirement was invalid but I was still curious what was going wrong on the request end of the test and thought it might be useful to log it here for record for me or others that might've needed the reference in the future. However, I thought you might be able to pinpoint it with little effort on your part. Thanks for the short dialogue, Matt.
