### ISSUE TITLE
Cookie Expires Time

### ISSUE THREAD

**Issue by Fruchtgummi** [gorilla/sessions#108]
I set a cookie with time for expired by login handling

`session.Options = &sessions.Options{
					Path:     "/",
					MaxAge:   3600,
					Secure:   config.Secure,
					HttpOnly: config.Httponly,
				}`

MaxAge: 3600

The cookie expire, even if I work on the site. What do not I understand?

**Comment by elithrar** [comment]
Can you show more code? did you save the cookie after the changes?

**Comment by Fruchtgummi** [comment]
Why more Code? I set the session Login...
`
value := map[string]string{
				"user_key": u.Key,
			}

			if encoded, err := cookieHandler.Encode("myname", value); err == nil {
				cookie := &http.Cookie{
					Name:     "myname",
					Value:    encoded,
					Path:     "/",
					Secure:   config.Secure,
					HttpOnly: config.Httponly,
				}
				http.SetCookie(w, cookie)

				session, err := sessionStore.Get(r, SessionName)
				if err != nil {
					handleSessionError(w, err)
					return
				}

				session.Options = &sessions.Options{
					//Domain:   config.Host,
					Path:     "/",
					MaxAge:   config.Cookieage,
					Secure:   config.Secure,
					HttpOnly: config.Httponly,
				}

				gravatarhash := getGravatar(r, u.Email)
				session.Values["user_key"] = u.Key
				session.Values["active"] = u.Active

				session.Values["vorname"] = u.Vorname
				session.Values["nachname"] = u.Nachname
				session.Values["email"] = u.Email
				session.Values["gravantar"] = gravatarhash
				session.Values["host"] = config.Host

				if err := session.Save(r, w); err != nil {
					handleSessionError(w, err)
					return
				}
`
How can I reset the timer? The cookieage expire sometime... :)

**Comment by elithrar** [comment]
The expiry is set when you send the cookie to the user - calling Save does
this.

If you want to refresh it you should have logic in your application that
saves it again.

**Comment by elithrar** [comment]
Closing out—if you still have problems, let me know.
