### ISSUE TITLE
Session slice stops accepting new items

### ISSUE THREAD

**Issue by ekkapob** [gorilla/sessions#109]
Are are any limit to the session? I have code below to append a new item to the slice. It works many items until some point I can't retrieve the new item data, like it stops accepting the new item after `save`. 

I tried to print out the session store after `session.save` the data are in there. But in another handler, it can't see the new item. I registered all of the structs with `gob`, still not working. I have no clue because it works and then stop working like the session doesn't accept the new slice item, but editing the existing value still works.

```
// order.List = []Item
order.List = append(order.List, Item{name: "abc"})
session["order"] = order
session.Save(r, w)
// print here shows the new added item
```

but another handle doesn't see the new added item.

**Comment by elithrar** [comment]
Are you using the CookieStore? Check the error from session.Save - you
might be hitting the 4KB size limit of a cookie.

**Comment by elithrar** [comment]
- If you increase the MaxLength for the CookieStore, browsers will not
accept your cookie - the typical max size per domain is 4KB.
- You can use the FilesystemStore instead, or one of the many third party
stores (https://github.com/gorilla/sessions#store-implementations) - the
Redis one being my personal go-to - but I would sanity check the rationale
for storing > 4KB per data per session as well.

**Comment by ekkapob** [comment]
Thank you @elithrar for the answer and advice. I end up do the checking and warn the user as they shouldn't keep adding (temporary) things.
