### ISSUE TITLE
API enhancement to make it easier to defend against session fixation attacks

### ISSUE THREAD

**Issue by cless** [gorilla/sessions#11]
I believe the session API could be improved to make defending against [session fixation attacks](http://en.wikipedia.org/wiki/Session_fixation) easier. It is currently possible to regenerate the session ID but it is a convoluted process that could really benefit from being documented and part of the API:

```go
// NOTE: session is already opened from a FileSystemSore, error 
// checking is left out for brevity.

// First save the session data to use in our new regenerated session
sessiondata = session.Values

// Next destroy the current session (or at least make it empty)
session.Values = make(map[interface{}]interface{})
session.Save() 

// Restore the session data and make sure it gets a brand new ID 
session.ID = ""
session.Values = sessiondata
session.Save()
```
Since session fixation attacks do not make sense against CookieStore sessions I'm not sure if it should go in the Session API or in the Store API. However, since it applies to (almost) every other store I would probably opt for the Session API.

I am willing to tackle this issue but I would like to discuss what the API should look like before I go ahead.

**Comment by elithrar** [comment]
The solution for this would be a `Reset()` method on the cookie that refreshes the ID, although I'm not entirely convinced it's a practical attack.

Marking help-wanted if there's interest.

**Comment by elithrar** [comment]
Going to close this due to inactivity (it's not a session fixation attack either).
