### ISSUE TITLE
ClearHandler + echo?

### ISSUE THREAD

**Issue by iKonrad** [gorilla/sessions#112]
Hi

I'm using echo library for HTTP routing. Would it be safe to use gorilla sessions with it? And how would you apply the ClearHandler wrapper to echo routes?

Thanks

**Comment by elithrar** [comment]
You won't need ClearHandler if you are using >= Go 1.7.

gorilla/sessions is otherwise OK to use with echo, but you will need to
pass echo.Context.Request as it wraps http.Request.

**Comment by elithrar** [comment]
Closing out—if you still have problems, let me know.
