### ISSUE TITLE
Am I doing something wrong or does it not work with Google Compute Engine (inside Docker container)?

### ISSUE THREAD

**Issue by dadatawajue** [gorilla/sessions#118]
It works perfectly locally, but when I try to run it on Compute Engine then nothing happens.. which, in my opinion, makes no sense because it's running inside a Docker container on Compute Engine. This is basically all the code:

```
var sessionStore = sessions.NewCookieStore(
	[]byte(securecookie.GenerateRandomKey(64)),
	[]byte(securecookie.GenerateRandomKey(32)))

func init() {
	sessionStore.Options = &sessions.Options{
		Domain:   "localhost",
		Path:     "/",
		MaxAge:   28800,
		HttpOnly: true,
	}
}

func GetSession(r *http.Request) *sessions.Session {
	session, _ := sessionStore.Get(r, "super-secret")
	return session
}
```

I have tried changing Domain from "localhost" to the specific Internal IP of the Compute Engine instance but it didn't work. I have also tried both with and without HttpOnly option..

Any help would be much appreciated (:

**Comment by elithrar** [comment]
Can you describe what doesn't work? Is the cookie not set on the client? Is
the server rejecting the cookies?

Note that you are generating a key each time the application starts and
thus you cannot read existing cookies. If you are scaling beyond 1 instance
in GCE then each instance won't be able to parse the cookies set by another
instance either.

**Comment by dadatawajue** [comment]
I mean locally I have no problem added flashes and setting session values, e.g.:

```
sess := session.GetSession(r)
..
sess.Values["user"] = username
sess.Save(r, w)
```

and it works locally when I then try to get the username with 

```
sess := session.GetSession(r)
log.Println(sess.Values["user"])
```

But on Compute Engine none of it works; I really feel it's strange it would work when running Docker on my machine but not when running Docker inside a Compute Engine instance.. I figure the only explanation must be that I maybe need to modify the &sessions.Options?

-----

About the NewCookieStore, that makes sense (guess that explains why I always have to re-login after restarting the app) :p.. is there any drawback to hardcoding the cookiestore as opposed to using securecookie.GenerateRandomKey(64) (assuming the hardcoded one have same length?

**Comment by kisielk** [comment]
For the domain I believe you need to be using the actual domain that the browser will see when accessing your site, otherwise it will not send the cookies back to the server.

**Comment by dadatawajue** [comment]
Ahh that worked.. tried the internal but not external IP.. thanks a lot <3
