### ISSUE TITLE
store.Get doesn't get session.

### ISSUE THREAD

**Issue by connelevalsam** [gorilla/sessions#119]
I am learning golang. I've done a little web app with the http.Cookie handler.
Read about gorilla/sessions and mux.
Decided to try the sessions out, but not saving session hence my login is not working.
Copied my code to playground so will paste the [link](https://play.golang.org/p/sDBVuVF39O)

**Comment by elithrar** [comment]
store.Get and session.Save return an error.

You should check those errors.

**Comment by connelevalsam** [comment]
@elithrar Thanks for the feedback, i checked the err but the admin/index.html is rendered even when am not logged in
Even though I checked cookie on my browser, nothing is created.
Yet the admin/index.html is rendering.
It is supposed to render the landing page first.
Then after login.
Based on the is_admin table in db.
The auth is set.
Now based on the auth
Render the rest of it all.

**Comment by elithrar** [comment]
You should also make sure you're saving the session before rendering the template.

**Comment by elithrar** [comment]
Closing out—if you still have problems, let me know.
