### ISSUE TITLE
sessions library can cause memory leak with Go 1.7+ even with ClearHandler or context.Clear()

### ISSUE THREAD

**Issue by Jackyjjc** [gorilla/sessions#122]
ClearHandler or gorilla/context.Clear() clears the registry using the request object as the key. However, the request object can be changed during its lifetime by the function introduced in Go 1.7+ [request.WithContext()](https://golang.org/pkg/net/http/#Request.WithContext). This function returns a shallow copy of the request object. Therefore, using gorilla/context.Clear() will not clear the entry in the registry if the request object has been changed. This has caused our app to leak request objects in production. Just a warning to everyone uses this library. 

The workaround is to use `gorilla/context.Purge(-1)` but this will clear all context for all requests  so it might cause issue. Alternatively your application have to save the old request object whenever you call Request.WithContext() and then clear the gorilla context with the original request object.

**Comment by Jackyjjc** [comment]
related PR: https://github.com/gorilla/sessions/pull/110

**Comment by elithrar** [comment]
Ideally we address this with a major version bump of gorilla/sessions that removes the old gorilla/context completely.
