### ISSUE TITLE
Sessions appear not to persist between calls to backend

### ISSUE THREAD

**Issue by patientplatypus** [gorilla/sessions#125]
I have found that sessions appear not to persist across multiple calls to the backend in Gorilla. I've seen a few open questions on stackoverflow addressing this problem, without working solutions given. I have linked to the full write up I provided on stackoverflow below, but given the number of outstanding questions on this issue, it may be a bug.

https://stackoverflow.com/questions/46759540/gorilla-sessions-does-not-persist-in-golang

**Comment by elithrar** [comment]
From a very quick glance, you seem to have implemented your own Store
backend that doesn’t persist data, instead of using the included
CookieStore?

**Comment by patientplatypus** [comment]
So...I thought that the way that I wrote config.KeyStore() may have been an issue so I rewrote it to the following and the persisted it throughout the project (I will update the stackoverflow question):

```
package config

import (
	"github.com/gorilla/sessions"
)

var SessionsStore = sessions.NewCookieStore([]byte("secret"))

func init() {
	SessionsStore.Options = &sessions.Options{
		Domain:   "localhost",
		Path:     "/",
		MaxAge:   3600 * 8, // 8 hours
		HttpOnly: true,
	}
}

```

So now wherever I need SessionsStore I just call conf.SessionsStore. That's seemingly as canonical a way to do it as I think is possible. I still have the same issue.

**Comment by patientplatypus** [comment]
I've narrowed down the issue significantly, so I will close and reopen.
