### ISSUE TITLE
Documentation: Need examples of secure / encrypted cookies

### ISSUE THREAD

**Issue by jrmiller82** [gorilla/sessions#130]
I'm scratching my head on how to get the `store.Options{Secure: true}` to work, and also how to get setting the encryption key in `sessions.NewCookieStore(key, enckey)` to work.

Maybe a code snippet in godoc near the `Options` type that shows some example code on how to use the secure bool?

**Comment by elithrar** [comment]
What issues are you having exactly?

• If you supply two keys (of the right lengths, as per the docs), the
library will both MAC and encrypt the cookie values.
• If you set yourstore.Options.Secure = true, cookies will be set with the
Secure attribute.

Are you not seeing this? How are you testing?

**Comment by jrmiller82** [comment]
I use `securecookie.GenerateRandomkey(32)` to generate my keys so they're of the right lengths. 

I can get the cookie to work fine with:

`var store = sessions.NewCookieStore(key, enckey)` 

and with `store.Options.Secure = false`

The minute I set `store.Options.Secure = true` it stops working. Maybe I'm misunderstanding something about cookies in general...

**Comment by jrmiller82** [comment]
Ahh. Looks like i'm testing over plain http and not https which would explain why the cookie isn't transmitting when the secure option is set to true.  My apologies.
