### ISSUE TITLE
Documentation: type Options needs better docs

### ISSUE THREAD

**Issue by jrmiller82** [gorilla/sessions#131]
Options type needs better clarification that `MaxAge: 0` will be deleted after the browser session ends. Or is it `MaxAge<0`?

**Comment by elithrar** [comment]
http://www.gorillatoolkit.org/pkg/sessions#Options

type Options struct {
Path string
Domain string
// MaxAge=0 means no 'Max-Age' attribute specified.
// MaxAge<0 means delete cookie now, equivalently 'Max-Age: 0'.
// MaxAge>0 means Max-Age attribute present and given in seconds.
MaxAge int
Secure bool
HttpOnly bool
}

Let me know if this could be clearer?

**Comment by jrmiller82** [comment]
// MaxAge=0 means no 'Max-Age' attribute specified and will be deleted after browser session ends.

**Comment by elithrar** [comment]
Submit a PR? ✨

**Comment by jrmiller82** [comment]
I will when I have some time.

**Comment by kshitij10496** [comment]
Thanks, @jrmiller82 for opening this issue.

I, myself, stumbled upon this behavior and wanted to incorporate it in the docs for future reference.
I will make the changes and send a PR real quick if it's fine by @jrmiller82. 😅

**Comment by BenJuan26** [comment]
Why are the other options not documented?
