### ISSUE TITLE
Enhancement request to add an exported Close method to the sessions.Store interface

### ISSUE THREAD

**Issue by devnull52** [gorilla/sessions#133]
Redis implementation of Gorilla session gopkg.in/boj/redistore.v1 exposes a Close function which can be deferred. Since Close function is not part of the Store interface. For the default CookieStore implementation it can be no-op ( do nothing ) and still allow other implementations to close DB and Redis connections cleanly.

var s sessions.Store

s,err = <package>.New<Impl>Store(receiver arguments)
defer s.Close()

**Comment by elithrar** [comment]
Adding to the existing Store interface would be a breaking change. You can
always assert the Store back to its concrete type and then call Close().

**Comment by kisielk** [comment]
Not something that could be easily solved with versioning either, since changing the interface would mean having to update and version all the store implementations too. Would be pretty ugly :/

**Comment by devnull52** [comment]
Thanks for both your responses. I realize it will be a breaking change and
eventually ended up referencing the concrete type and defer on it. Perhaps
worth considering if there is a way to include it in future. Thanks, we may
close the issue given the comments.
