### ISSUE TITLE
Cookies not sent on heroku

### ISSUE THREAD

**Issue by moar55** [gorilla/sessions#134]
Hi,
I am using beego to create an API and I am using gorilla sessions as they were working better than the beego's sessions for me. The problem is it's working fine on localhost, but after I deployed to heroku no cookie is sent in the server response. Any clues?

**Comment by elithrar** [comment]
Can you show your code, and a copy of the request/response? Are any cookies
set in the browser?

**Comment by moar55** [comment]
Hi,
The issue is resolved now. It was a problem with the db connection going idle, which affected code execution. I will close the issue, thanks.
