### ISSUE TITLE
Expired sessions

### ISSUE THREAD

**Issue by rvillablanca** [gorilla/sessions#136]
Currently is there any way expired sessions are removed ? For example if I am using Redis or Mysql store for my session, how are session deleted if only one request reach to my application and then it never back ?

**Comment by rvillablanca** [comment]
I don't know if expired sessions are removed after certain time or I need to implement my own backgroud process that remove all expired sessions, independent of any store.

**Comment by elithrar** [comment]
These are questions for those particular stores, but I can answer on behalf of the [Redistore](https://github.com/boj/redistore) store - 

* `store.Options.MaxAge` or `session.MaxAge` will define the global or per-session TTL
* The Redistore uses the Redis [SETEX](https://redis.io/commands/setex) command when saving a session, as per here: https://github.com/boj/redistore/blob/master/redistore.go#L327 - which means that Redis will automatically clean up those expired keys.
