### ISSUE TITLE
I can't seem to get this to work. Thanks!

### ISSUE THREAD

**Issue by happilymarrieddad** [gorilla/sessions#144]
Hey guys,

I'm sure I'm just doing something wrong but I can't seem to get this to work. Basically, I want to use Go as my backend and vuejs as my frontend.

Go Session Code
![selection_008](https://user-images.githubusercontent.com/6416323/36329254-98ca7256-1322-11e8-9421-bd0f19a918dd.png)
![selection_007](https://user-images.githubusercontent.com/6416323/36329256-9b7dd3f8-1322-11e8-950a-17de80f3122e.png)
![selection_010](https://user-images.githubusercontent.com/6416323/36329274-ac157946-1322-11e8-90a6-9c3b2133c229.png)
![selection_009](https://user-images.githubusercontent.com/6416323/36329264-a3c5a75c-1322-11e8-9e7c-c9f708f27fec.png)
![selection_011](https://user-images.githubusercontent.com/6416323/36329285-b7b51cde-1322-11e8-9d78-cc89be2f7e77.png)

When I refresh my app, the middleware always says the session is empty
![selection_012](https://user-images.githubusercontent.com/6416323/36329324-d8b1ac22-1322-11e8-9e25-d1fbb632ff15.png)

Also, there are always new entries in my database... it never finds the same one it was using before.
![selection_013](https://user-images.githubusercontent.com/6416323/36329706-2a001266-1324-11e8-8ee8-b3142c504c28.png)

**Comment by elithrar** [comment]
Could you please post this as code blocks (text) and not images? Much
(much!) easier to help you!

**Comment by elithrar** [comment]
Also, from a quick look, I can see no evidence you are calling
session.Save, which will never write the cookie back to the client.

**Comment by happilymarrieddad** [comment]
@elithrar oh so sorry man.

If you look at the store function about 2/3 of the way down I call session.Save.

**Comment by happilymarrieddad** [comment]
`
func Store(w http.ResponseWriter, r *http.Request) {
	var login Login
	decoder := json.NewDecoder(r.Body)
	if err := decoder.Decode(&login); err != nil {
		log.Println(err)
		http.Error(w, "Unable to get vars", http.StatusBadRequest)
		return
	}

	user, err := Users.FindByEmail(db, login.Email)
	if err != nil {
		log.Println(err)
		http.Error(w, "Unable to find account", http.StatusUnauthorized)
		return
	}

	if user.Id < 1 {
		log.Println("User id less than 1")
		http.Error(w, "Unable to find account", http.StatusUnauthorized)
		return
	}

	session, err := store.Get(r, os.Getenv("SESSION_NAME"))
	if err != nil {
		log.Println(err)
		http.Error(w, "Unable to get session data", http.StatusUnauthorized)
		return
	}
	session.Values["user_id"] = user.Id
	log.Println(session.Values)
	if err = session.Save(r, w); err != nil {
		log.Println(err)
		http.Error(w, "Unable to save session data", http.StatusUnauthorized)
		return
	}

	payload, err := json.Marshal(user)
	if err != nil {
		log.Println(err)
	}

	log.Println("Sending data back to the client")
	session, _ = store.Get(r, os.Getenv("SESSION_NAME"))
	log.Println(session.Values)

	w.Header().Set("Content-Type", "application/json")
	w.Write(payload)
}`

**Comment by happilymarrieddad** [comment]
Could it be that i'm using Axios and it's not saving a cookie in the browser?

**Comment by happilymarrieddad** [comment]
I'm going to go with websockets and abandon http for now.. I like them better anyways. Thanks!

**Comment by happilymarrieddad** [comment]
Does gorilla/sessions set httponly:true by default? Maybe, axios can't see it because of that? Thanks

**Comment by l9f** [comment]
@happilymarrieddad That's likely the issue. What does the cookie say in Firefox's inspector?

**Comment by happilymarrieddad** [comment]
@l9f Hey man, how do I turn that off? Thanks!

![selection_014](https://user-images.githubusercontent.com/6416323/36332085-fb5d3b96-132d-11e8-80d4-94989ac2bd5b.png)

**Comment by happilymarrieddad** [comment]
Also, do you know where the weird name came from? asgdfgdf

**Comment by l9f** [comment]
```
func MyHandler(w http.ResponseWriter, r *http.Request) {
    // Get a session. Get() always returns a session, even if empty.
    session, err := store.Get(r, "session-name")
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    // Set some session values.
    session.Values["foo"] = "bar"
    session.Values[42] = 43
    // Save it before we write to the response/return from the handler.
    session.Save(r, w)
}
```

Somewhere in your code you'd have something like that and you set the session name to asdfasdfasdf etc... 

And to change the http only flag you need to set the Options:

http://www.gorillatoolkit.org/pkg/sessions#Options

**Comment by happilymarrieddad** [comment]
Hmm, @l9f hey man thanks for the info but I think I'm going with websocket session. I know how to get that to work easily enough. Thanks!
