### ISSUE TITLE
v1.1 tag format is not vgo-compatible

### ISSUE THREAD

**Issue by eandre** [gorilla/sessions#156]
Hey,

I tried to use this library with vgo but ran into some trouble because the tag `v1.1` is not compatible: vgo expects SemVer tags to be three digits (`v1.1.0`). Would it be possible to tag a new release using this format for easier integration with vgo?

Thanks so much :)

**Comment by elithrar** [comment]
Ah! Will fix tonight when back from work.

**Comment by elithrar** [comment]
Done! https://github.com/gorilla/sessions/releases/tag/v1.1.1
