### ISSUE TITLE
how to sync session to another node

### ISSUE THREAD

**Issue by lezi1022** [gorilla/sessions#159]
is there a way sync session to another node?

**Comment by elithrar** [comment]
Two options:

- Use the same session key with the CookieStore, which will allow all nodes with that key to read/write the same cookie 
- Use a server side store that supports multiple concurrent clients: https://github.com/gorilla/sessions/blob/master/README.md#store-implementations

**Comment by lezi1022** [comment]
dear elithrar, the second choose is base on store sync,  our system is base on redis, and deploy to two datacenter, and the two redis can't to be one cluster because any redis will accept write opration,  redis hasn't master-master cluster.  so i want to double write to two redis, but there is no api for me to write remote store

**Comment by elithrar** [comment]
If that’s the case, don’t use Redis for this.

Also think about whether a single user is going to bounce between data
centers: it’s likely they they do not need to at all.

Using cookies would prevent the need for syncing.
