### ISSUE TITLE
How to delete my session

### ISSUE THREAD

**Issue by dimensi0n** [gorilla/sessions#160]
Here is my login handler : 
```golang
var store = sessions.NewCookieStore([]byte("123456"))
r.HandleFunc("/login", func(w http.ResponseWriter, r *http.Request) {
		r.ParseForm()
		session, err := store.Get(r, "user")
		fmt.Println(session.Values["username"])
		if session.Values["username"] != "" {
			http.Redirect(w, r, "/home", 301)
		} else {
			if login.Login(r.Form["username"][0], r.Form["password"][0]) == true {
				if err != nil {
					panic(err)
				}
				session.Values["username"] = r.Form["username"][0]
				session.Values["password"] = r.Form["password"][0]
				session.Save(r, w)
				http.Redirect(w, r, "/home", 301)
			} else {
				http.Redirect(w, r, "/relogin", 301)
			}
		}
	}).Methods("POST")
```

And I want the disconnect handler to delete the session and I didn't see how to do that in de documentation...

**Comment by weivall** [comment]
You can use MaxAge
https://github.com/gorilla/sessions/blob/03b6f63cc43ef9c7240a635a5e22b13180e822b8/store.go#L116

**Comment by elithrar** [comment]
Also covered in the docs: http://www.gorillatoolkit.org/pkg/sessions#CookieStore.MaxAge (search for "delete").

Closing for now, but reply if any follow-up questions!

**Comment by HarikrishnanBalagopal** [comment]
> Also covered in the docs: http://www.gorillatoolkit.org/pkg/sessions#CookieStore.MaxAge (search for "delete").
> 
> Closing for now, but reply if any follow-up questions!

This link is dead now

**Comment by HarikrishnanBalagopal** [comment]
and https://github.com/gorilla/sessions/issues/211
