### ISSUE TITLE
Unable to set sameSite=strict for cookies

### ISSUE THREAD

**Issue by tirithen** [gorilla/sessions#164]
I'm unable to set sameSite cookie option to strict to prevent cross-site requests from sending out the cookie, an thoughts on how to add that feature? 

https://www.owasp.org/index.php/SameSite

**Comment by elithrar** [comment]
This isn’t yet exposed in the underlying securecookie library, as it was
only just supported in Go 1.11’s http.Cookie (literally two days ago).

I plan to add support to both within the next week or so.

**Comment by tirithen** [comment]
Wow thanks, I did not realize this. Looking forward for this :)

**Comment by elithrar** [comment]
Closing in favor of #165 - PR is building in CI & in review.
