### ISSUE TITLE
How to persiste cookies created with gorilla/sessions?

### ISSUE THREAD

**Issue by DawidCyron** [gorilla/sessions#169]
I'm creating a sign in system, where after logging in client receives a session. The problem is, the value of the cookie is changing every time I send a request (using Postman to test the API). Is it a thing with gorilla/sessions that it doesn't refresh session and creates new one, or is it something on my side?

**Comment by elithrar** [comment]
Can you share your code?

If you save the cookie each time, it will be “refreshed”, which includes
writing out a new cookie and signature.

**Comment by DawidCyron** [comment]
I guess you already answered my question. I am saving the cookie on every request, but I thought it would be refreshed in a way which saves the value field of a cookie (the long set of characters) and simply changes the expiration time. Is there any way to do it out of the box? If not, what is the best way to associate the session cookie with user in Redis when it's changing on every request?

**Comment by elithrar** [comment]
Are you using the Redis store, that handles this for you? It will issue
deterministic IDs and store the cookie value in Redis:
https://github.com/boj/redistore (linked from the README)

The reason it changes is because cookie values are signed (for security);
changing the timestamp changes the signature. You definitely don’t want to
change that behavior.

**Comment by DawidCyron** [comment]
May I publish a link to the code here tomorrow?

**Comment by elithrar** [comment]
Can you clarify what you mean? Do you want me to review your code? (are you using the Redis store I listed above?)

**Comment by DawidCyron** [comment]
If you could help me review my code, I would be thankful. You can find it [here](https://play.golang.org/p/xN1jNTDi1pB). The problem that I'm encountering is: on my testing website I receive a cookie and it's saved. The problem then appears when I hit the API again. The completely new cookie is generated, but not saved into Redis. Cookie is then saved only if I completely remove cookie from browser and hit API again. Am I using any of the libraries in a wrong way? Also, while you're at it, could you tell me what you think about the readability of my code?

**Comment by elithrar** [comment]
Before I dive deeper later today: remove lines 65-68 where you
re-initialize the Redis store after already initializing it in your main()
function.

You should initialize the store once at startup and pass the Store around,
or have it as a package global variable (as you do at the top on line 20).

**Comment by DawidCyron** [comment]
The problem is, when I delete this line I get this error: 
2018/09/21 16:39:16 http: panic serving 127.0.0.1:53042: runtime error: invalid memory address or nil pointer dereference
Maybe it's something else in the code that I just don't see

**Comment by elithrar** [comment]
You’re shadowing your package global in your main() function.

Where you call:

store, err := redistore.New...

You should have:

var err error
store, err = redistore.New...

Note the assignment and not the initialize+assignment.

**Comment by DawidCyron** [comment]
Great, thanks, that helped. What do you think about the rest of the code (I know, not much but that's just the start)? Also, could you tell me how the cookie is recognized and associated with session? I thought that the value of the cookie was the same as session ID.

**Comment by elithrar** [comment]
OK, apologies for taking so long to look at this: I've been travelling the
last few days.

General comments:

- You call panic(err) a lot, when you would be better off logging the error
(clearly, not obscured by the stack trace) and then existing. log.Fatal is
good for this.
- Your handlers make the extremely common mistake of logging errors, but
*continuing on*. In a handler, you probably want to bubble the error up,
call http.Error with an appropriate status code, and *then explicitly
return*.
- Take a look at a post I wrote up on how to make this clearer: harder to
"forget" to return, and easier to pass in your dependencies:
https://blog.questionable.services/article/http-handler-error-handling-revisited/

Hope that helps!
