### ISSUE TITLE
How to handle err from  store.Get()

### ISSUE THREAD

**Issue by MichaelHipp** [gorilla/sessions#179]
The docs say this about about `func (*CookieStore) Get`: "It returns a new session and an error if the session exists but could not be decoded." Two questions...

- What is the correct way to handle this? Return 'Forbidden'? 'InternalServerError'? Accept the session and proceed with it?

- Are there any other errors that can be returned by store.Get()?

**Comment by andrewpillar** [comment]
Failure to get a session would suggest an internal error of the server itself, so `InternalServerError` would perhaps be the best error code to return.

**Comment by elithrar** [comment]
I typically return a HTTP 400, but 500 could be “correct” under the right
circumstances:

• Client submits a malformed cookie (bad signature, too large, etc) - 400
• Can’t read from the backing datastore (if server side sessions) - 500

There’s not a great way to discern between these underlying reasons—Go’s
error handling doesn’t simplify it + server side libraries have to bubble
up typed errors—although the securecookie library does have (many) error
types if you want to be fine-grained.
