### ISSUE TITLE
Registry.Get does not handle Store failure well.

### ISSUE THREAD

**Issue by qedus** [gorilla/sessions#18]
If the session store fails with an error, the registry code https://github.com/gorilla/sessions/blob/master/sessions.go#L147-L149 completely ignores it and still tries to access the session. This works fine so long as a CookieStore.New implementation never return nil (which should be explicitly documented). However there may be cases when the session just can't be retrieved and we don't want it automatically saved in the Registry.

**Comment by carbocation** [comment]
Actually, I think that solving this might be necessary for fixing Issue #161 if I have diagnosed it correctly.
