### ISSUE TITLE
Missing go.sum?

### ISSUE THREAD

**Issue by ciehanski** [gorilla/sessions#183]
It appears this package is using the now recommended _go modules_, but has failed to include the go.sum file which is recommended to be checked into version control. 
  
From https://github.com/golang/go/wiki/Modules#releasing-modules-all-versions:
> Ensure your go.sum file is committed along with your go.mod file. See FAQ below for more details and rationale.
  
Just bringing this to attention.

EDIT: browsing through most of the gorilla repositories, and this seems to be a recurring theme.

**Comment by elithrar** [comment]
FYI, for context: `go.sum` was not generated at the time we started to use Modules. Most repos have added & committed it since.
