### ISSUE TITLE
Data-Limit on Session?

### ISSUE THREAD

**Issue by Fruchtgummi** [gorilla/sessions#186]
Hi,

is the size of Session size limitated?

I use follow packages:

"github.com/gorilla/csrf"
"github.com/gorilla/sessions"
"github.com/philhofer/securecookie"

I register a gob for a language object. The struct of language-object have 50 rows, but if I do one row more, then is the session empty!

**Comment by elithrar** [comment]
It depends on the session store. Cookies are limited to 4KB per domain in most browsers.

This is documented https://godoc.org/github.com/gorilla/securecookie#SecureCookie.MaxLength in securecookie, which sessions also uses, and is the default.

**Comment by Fruchtgummi** [comment]
Thanx!
