### ISSUE TITLE
[suggestion] HTTPOnly default to true

### ISSUE THREAD

**Issue by swaroopdeval** [gorilla/sessions#187]
As we know that HTTPOnly cookies are more secure and for sessions we should always keep them HTTPOnly, Can we make HTTPOnly default value to true in NewCookieStore method in sessions/store.go?
Or we should add options argument in NewCookieStore, same as we do with NewCookie method of sessions/sessions.go

**Comment by elithrar** [comment]
Note that you can set the "default" at the store-level after you create it
- e.g.

var store = NewCookieStore(authKey)
store.Options.HttpOnly = true

I'm not opposed to making it the default in a new release, although it both
needs to be documented as the default in the README, and have a clear line
in the release notes, as it *is* a breaking change for some users.
