### ISSUE TITLE
Username and Password in session cookie

### ISSUE THREAD

**Issue by rubyman** [gorilla/sessions#189]
Do you storing Username and Password in a Cookie? This behavior increases the risk that users' passwords will be captured by an attacker. Any cookie-stealing vulnerabilities within the application or browser would enable an attacker to steal the user's credentials to the application.

**Remediation :** 
Applications should not store user credentials within any client-side mechanism such as cookies.

**Vulnerability classifications :** 
[CWE-287: Improper Authentication](https://cwe.mitre.org/data/definitions/287.html)

**Comment by elithrar** [comment]
Applications should not store passwords or tokens in cookies - cookies are not designed for that.

**Comment by rubyman** [comment]
I investigated an application that used your library and after decoding a cookie i found username and password.Is it possible a developer  to customize the cookie content?

**Comment by elithrar** [comment]
Developers can store any values in the session.Values map - there is no
reasonable way to prevent that as this library does not perform authn/authz.
