### ISSUE TITLE
how to get user id?

### ISSUE THREAD

**Issue by sadegh-shahbazi** [gorilla/sessions#190]
I use this package and i can realize if any body signed in or no...
but I cant understand how should I get user ID?
if I put the user ID in another cookie, user can change it... and login as another user
is this code safe:
session.Values["userid"] = loggedInUser.ID

**Comment by elithrar** [comment]
Cookies are signed (authenticated); which means that users cannot modify
them without an error:

> Simple API: use it as an easy way to set signed (and optionally
encrypted) cookies

**Comment by sadegh-shahbazi** [comment]
thank you
