### ISSUE TITLE
Garbage in, silent failing ...  

### ISSUE THREAD

**Issue by adamjack** [gorilla/sessions#193]
Two cases where I'd like things to fail harder/earlier (maybe if in some development mode.)

Per suggestion I pass the session key in from the environment. Once I failed to set it in the environment and sessions failed silently. Should the NewCookieStore method reject an empty/missing or mis-lengthed string, maybe panic'ing? It would've saved me a lot of head scratching. :-) I added code like below, but hopefully you'd check the multiple key length options:

var sessionKey = []byte(os.Getenv("SESSION_KEY"))

	// Cannot run without a session key...
	if 0 == len(sessionKey) {
		panic("Wot no SESSION_KEY?")
	}
	if 16 != len(sessionKey) {
		panic("Wot sort of SESSION_KEY?")
	}

Additionally I didn't look at the signature of Save(w,r) and didn't know (for too long) that it was failing. Again, maybe in some development mode, it could panic failing faster.

**Comment by kisielk** [comment]
I don’t think that panicking without a session key is appropriate. In my opinion panicking should be primarily used for programming errors. Failing to provide a session key in the environment is a runtime error. Save will return an error if a key is not provided. 

With regards to Save, you should be checking errors. There’s a lot of functions in Go that return errors and they should always be checked, it wouldn’t really make sense for all of them to add a development mode where they panic, as that would simply break a lot of normal code flow. There are tools, like kisielk/errcheck, that you can use in your development flow and ensure you have checked errors.

**Comment by adamjack** [comment]
Hi @kisielk thanks for the input.

It was suggested that I post this thought here, so I did so to be polite. I should've taken the time to be clear that I am not a Golang expert aware of good/bad Go practices, but a newbie who stumbled on these two things (and it took me a long time to figure them out.) 

That said, as a newbie I prefer things to fail early. I like being hit by a two by four for my newbie mistakes :-) so I learn quicker. Sessions failing silently is not helpful - it took ages for me to understand why - and personally I think I'd argue for a panic even in production 'cos silent failure is just as damaging, arguably more so. Why cost production potentially hours of bad running and ages of debugging for something that the sessions code know is seriously off (a missing session key.) 

I agree I should check for errors on Save, but I stumbled upon a sample that didn't and copied it and (as a newbie) didn't know the method returned an error. Yes, bad sample, but I didn't create it, I just stumbled upon it. It took me a lot of reading (finally coming to the discussion here) to see somebody mentioned the errors it returned, and so I immediately checked it.

The idea of some sort of "two by four hitting panic for developer mode" is just something I was throwing out, but I do think that "developer errors" (I was passing a type that could not be serialized, that is never going to work) should be slapped loud and hard. As such, some sort of "debugging" or "development" flag that could be set to allow louder (stderr? panic?) complaints is just the general idea.

Thanks for your consideration. Just passing in my newbie experience for your / the team's consideration.

**Comment by adamjack** [comment]
BTW: The sample I used was from here:

   https://www.gorillatoolkit.org/pkg/sessions

... and I do (now) see that later the text says "in production we should check errors", but I was in newbie / tinkering / learning mode and just wanted to get a feel for the code, and missed that sentence. Maybe those samples could at least be _ = session.Save( ... in order to clue people in to there being an important return value.

**Comment by elithrar** [comment]
100% agree that the examples should be updated. Are you interested in submitting a quick PR for `doc.go`, @adamjack? 😉

**Comment by adamjack** [comment]
Ok @elithrar so I should just change them to be _ = session.Save(... to indicate there is a return?

**Comment by adamjack** [comment]
Hmm, I see one Save in the README.md on GitHub but I don't see where I can edit the page here:

    https://www.gorillatoolkit.org/pkg/sessions

... happy to make the change if you can point me to where I can.

**Comment by adamjack** [comment]
Forgive me if I did things incorrectly (I'm new to doing this) but here is a simple attempt at a PR for a single _ = in README.md:

    https://github.com/gorilla/sessions/pull/197

**Comment by elithrar** [comment]
Show the error handling - e.g. err := session.Save(...)

doc.go is what generates the website docs.

**Comment by adamjack** [comment]
I used _ = in the README.md 'cos I didn't want to clutter the simple usage message, and I used err = in the docs.go (using = not := 'cos err was already defined) and error handling for these samples. Please let me know if that should be changed. I believe I've updated the PR.

**Comment by adamjack** [comment]
Can the associated pull request be merged in? It is pretty innocuous (since it impacts documentation only) and it seems it might expire otherwise.
