### ISSUE TITLE
[question] response always set-cookie

### ISSUE THREAD

**Issue by marktohark** [gorilla/sessions#198]
**Describe the problem you're having**
every response reset session.
is this normal?

![未命名](https://user-images.githubusercontent.com/19359934/61144656-055fda00-a508-11e9-8c54-cb47fe7b09b7.png)
![未命名](https://user-images.githubusercontent.com/19359934/61144681-20324e80-a508-11e9-95e4-015c0ddb1a84.png)
![未命名](https://user-images.githubusercontent.com/19359934/61144698-30e2c480-a508-11e9-97b2-a2c51ed62b11.png)

**Versions**
go version go1.12.5 windows/amd64
github.com/gorilla/mux v1.7.3
github.com/gorilla/sessions v1.2.0

…

**"Show me the code!"**
```
package main

import (
	"fmt"
	"net/http"
	"github.com/gorilla/mux"
	"github.com/gorilla/sessions"
)

var store = sessions.NewCookieStore([]byte("something-very-secret"))

func MyHandler(w http.ResponseWriter, r *http.Request) {
	session, err := store.Get(r, "s1")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	fmt.Println("vv => ", session)
	session.Values["name"] = "kingeastensun"
	session.Save(r, w)
}

func MultiSessionHandler(w http.ResponseWriter, r *http.Request) {
	session1, err := store.Get(r, "s1")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	fmt.Println("kk => ", session1)
	session1.Values["name"] = "kingeastensun"

	session2, err := store.Get(r, "s2")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	fmt.Println("kk => ", session2)
	session2.Values["name"] = "kingeastensunyx"
	sessions.Save(r, w)

}

func main() {

	routes := mux.NewRouter()
	routes.HandleFunc("/session", MyHandler)
	routes.HandleFunc("/musession", MultiSessionHandler)

	http.Handle("/", routes)
	http.ListenAndServe(":5655", nil)
}

```

…

**Comment by elithrar** [comment]
Yes: if you call sessions.Save(r, w) every time, it will write a cookie to
the response.

This is typically OK: you are keeping the user logged in. If you don’t want
to do that, wrap Save with logic that suits your application.

**Comment by marktohark** [comment]
ok,thanks.
