### ISSUE TITLE
How to correctly delete/override cookie

### ISSUE THREAD

**Issue by cdtj** [gorilla/sessions#211]
I'm starting to work with gorilla/sessions from this example: https://github.com/CurtisVermeeren/Gorilla-Sessions-Tutorial/blob/master/CookiestoreSession/main.go

Where we have this part:
```
session, err := store.Get(r, "cookie-name")
if err != nil {
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}
```
But if cookie became invalid (user modified value, store keys changed, store file corrupted), this causes failure until user manually cleans the cookies.

I manually set empty cookie using http lib:
```
http.SetCookie(w, &http.Cookie{
	Name:     "cookie-name",
	Value:    "",
	Path:     "/",
	Expires:  time.Unix(0, 0),
	HttpOnly: true,
})
http.Redirect(w, r, "/", http.StatusFound)
```

But are there tools that designated to work with invalid cookies?

**Comment by elithrar** [comment]
If you get an invalid cookie, you should consider:

• Redirecting the user to a page to re-authenticate
• (and/or) returning an error indicating why

You should assume that an invalid cookie is potentially malicious - and
treat the user as unauthenticated.

If you set a cookie (save a session) then it will overwrite existing
cookies of the same name + origin (domain) pairing.

**Comment by cdtj** [comment]
@elithrar, thank you for the quick response, but is there a method to do that within the _gorilla/sessions_ package? 
I tried to set them to be expired but was unable to save because the session was not acquired.
```
if err != nil {
	session.Options.MaxAge = -1
	session.save(r, w) // remove sessions/session_: no such file or directory
	// or 
	// store.MaxAge(-1)
	// store.Save(r, w, session) 
	// same err  here: remove sessions/session_: no such file or directory
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}
```

**Comment by elithrar** [comment]
Calling `store.New` will help here: https://godoc.org/github.com/gorilla/sessions#CookieStore.New

**Comment by cdtj** [comment]
Sorry if I'm carrying too much about the situation that shouldn't happen for regular users, but:
1. init cookie by visiting website;
2. using dev tools modify to invalid;
3. re-access the website.

```
func getSession(w http.ResponseWriter, r *http.Request) *sessions.Session {
	session, err := store.Get(r, "wsdl")
	if err != nil {
		log.Printf("store.Get err: [%s], session.ID: [%s]", err, session.ID)
		session, err = store.New(r, "wsdl")
		if err != nil {
			log.Printf("store.New err: [%s], session.ID: [%s]", err, session.ID)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return nil
		}
	}
	log.Printf("session.ID: [%s]", session.ID)
	return session
}
```
```
// before cookie modification
2020/04/08 00:17:59 session.ID: [3B5VAC63RKEEJFJZ7KWQLXNXOIVRQKWHUM3TNNPXAVSVHLTPB2PA]
// after cookie modification
2020/04/08 00:18:25 store.Get err: [securecookie: base64 decode failed - caused by: illegal base64 data at input byte 0], session.ID: []
2020/04/08 00:18:25 store.New err: [securecookie: base64 decode failed - caused by: illegal base64 data at input byte 0], session.ID: []
```
Both methods returning the same error and session id wasn't inited too.
