### ISSUE TITLE
IsNew is always true

### ISSUE THREAD

**Issue by undeadindustries** [gorilla/sessions#212]
I'm really sorry to ask this question. I've spent days on this.

So far I've tried Cookie sessions and FireStore Sessions.
No matter what I do, Is New is always true
It's a pretty straight forward web site.
Session.Get is called to get or create the session.

Soon after entering the site, a WebSocket is created and the connection is put into a struct.
type socket struct {
	conn        *websocket.Conn
	session     *sessions.Session
	httpRequest *http.Request
	httpWriter  http.ResponseWriter
}

I do this so I can access the session and httpRequest after the websocket is created.
The reason I need the session is I use the ID. I need to know who each websocket is for so I can route to them when needed and delete them from the "online" list when done.

Because of that, when a websocket is connected, I save certain data into the session each time. Meaning, session.Save is run.

As I refresh the webpage, I can see new sessions just piling up.

**Versions**
> Go version: 1.14

> package version: 15ff3511704639ab26f7843f780c015f4bf49565
**"Show me the code!"**
```
client := socket{}
	client.conn, err = upgrader.Upgrade(w, r, nil)
	if err != nil {
		http.Error(w, "Could not open websocket connection", http.StatusBadRequest)
	}

	client.session, err = getSession(w, r)
	client.httpRequest = r
	client.httpWriter = w
```

```
func init() {
	ctx := context.Background()
	var err error
	sessionStore, err = firestoregorilla.New(ctx, firestoreClient)
	if err != nil {
		log.Panicf("Failed to connect to the session store: %v", err)
	}
}
func getSession(w http.ResponseWriter, r *http.Request) (*sessions.Session, error) {
	session, err := sessionStore.Get(r, "sessions")
	checkErr(err)
	if session.IsNew == true {
		log.Println("New Session")
		session.Values["authenticated"] = 0
		session.Values["email"] = ""
		t := time.Now()
		session.Values["created"] = t.String()
		session.Values["updated"] = t.String()
		if err := session.Save(r, w); err != nil {
			log.Printf("Save: %v", err)
			// Don't return early so the user still gets a response.
		}
	} else {
		log.Println("Got old session")
	}
	return session, err

}
```

```
s.Values["authenticated"] = 1
s, err := getSession(client.httpWriter, client.httpRequest) //not using client.session because I'm just sorting out why session is always new.
if err := s.Save(client.httpRequest, client.httpWriter); err != nil {
			log.Printf("Error Saving Session: %v", err)
}
```

THANK YOU!

**Comment by undeadindustries** [comment]
My session name and key is the same each time. I'm not changing it.

**Comment by elithrar** [comment]
Are you testing this in a browser?

**Comment by undeadindustries** [comment]
(Thanks for the quick response!)
Yes, latest version of chrome. 

I don't see the session in the browser either. I just created a very simple app as a sanity check, and I'm getting the same results there. No sockets or anything like that. Just a handler that creates a new cookie store and saves a value.

The crazy thing is that I could have swore this worked yesterday.

**Comment by undeadindustries** [comment]
Here is that quick test:
```

package main
import (
     "fmt"
     "log"
    "net/http"
    "github.com/gorilla/sessions"
)

// Note: Don't store your key in your source code. Pass it via an
// environmental variable, or flag (or both), and don't accidentally commit it
// alongside your code. Ensure your key is sufficiently random - i.e. use Go's
// crypto/rand or securecookie.GenerateRandomKey(32) and persist the result.
// Ensure SESSION_KEY exists in the environment, or sessions will fail.
var store = sessions.NewCookieStore([]byte("mytest"))

func MyHandler(w http.ResponseWriter, r *http.Request) {
    // Get a session. Get() always returns a session, even if empty.
    session, err := store.Get(r, "thetest")
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    // Set some session values.
    session.Values["foo"] = "bar"
    session.Values[42] = 43
    // Save it before we write to the response/return from the handler.
    err = session.Save(r, w)
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    fmt.Fprintf(w , "id: %+v",session.ID)
}

func main() {
fmt.Println("Running")
 http.HandleFunc("/", MyHandler)
 log.Fatal(http.ListenAndServe(":8444",nil))
}
```

**Comment by undeadindustries** [comment]
I just copied the test to local WSL and tested in Edge to make sure Chrome or the linux server aren't a variable in this. I also added session.Values["foo"] to the response. This is all I get when I go to localhost:8444

`id: . Foo: bar`

So same error there. This is so strange!

**Comment by undeadindustries** [comment]
I'm happy to test a different branch, if you like,

**Comment by elithrar** [comment]
I won’t have time to test until later today, but from first glance I’m
surprised the cookie doesn’t save.

a) is there a Set-Cookie header in the response?
b) can you see the cookie in Chrome DevTools > Application > Cookies?

**Comment by undeadindustries** [comment]
Thanks for the response.

In the simple test, I do see the test cookie. 

In the real app, I do not. I only see .google cookies. I am using Google API for login auth. Could that somehow be interfering? Possibly the websocket could have something to do with it? It's connected almost right away.

Also, possibly Cookies don't have IDs because they are on the client side and are only referred to by name?

I've triple checked my application. The cookie name never changes. But is also not what I set it to be. I have it a really long name. But when I printf session.Name, I get 0x527be0. Which I thought was strange. And still, no matter what, .Get results in IsNew as true.

Just throwing this out there, I'm totally open to allowing you to remote in and seeing this for yourself.

**Comment by elithrar** [comment]
You have to save the cookie BEFORE the websocket connection is active -
once the WebSocket has hijacked the connection you don’t have access to the
HTTP response headers, because WebSockets don’t have headers.

**Comment by undeadindustries** [comment]
Ahh. I need to rethink how this app works.
I'll update it today and update this issue. (And probably close/comment)

However, if you have any advice on how to keep track of who has which socket, I'd appreciate it. 
I've looked over the gorilla chat example. What it doesn't have is session like info. ie: "securely" storing someone's name or something like that, so when conn.close() is run, I can delete conns[username]*conn. If that makes sense?

I thought something like this would work.
type socket struct {
	conn        *websocket.Conn
	session     *sessions.Session
	httpRequest *http.Request
	httpWriter  http.ResponseWriter
	username       string 
}

But it won't because I don't get username until after the socket is connected. 

Thanks again for all your responses.

**Comment by elithrar** [comment]
Think of the connection flow this way:

1. Client "dials" a WebSocket address [initiated by a HTTP request]
2. The server, if it agrees, sends a HTTP response with the relevant Upgrade: websocket header and any other response headers. This is your "last" opportunity to do anything at the HTTP level with the client directly.
3. From here on, all transport over this connection is WebSocket, not HTTP - the WebSocket "hijacks" the TCP connection.

At step no. 1, the client may send the server a cookie, if it has one. At step no. 2, the server may respond with Set-Cookie header (or reject the WebSocket upgrade). This is how you would "know" who the client is.

Each "client" would be represented by something closer to:

```go
type ClientConn struct {
    conn *websocket.Conn
    id string // e.g. some unique identifier that you use to associate this conn with a "user" - a user might have > 1 active connection!
    // other fields - maybe "lastActive" or other state you want to carry
}
```

As for "session data", you should prefer server-side session backends (e.g. FileSystemStore, or Redis, etc.) - that way, the client only needs an ID into that session via a simple cookie or API token. You can "refresh" that cookie _during the WebSocket connection_ by running XHR ("AJAX") requests on the same page/view to the server, and having the server call `session.Save` there. That would still be a _distinct_ connection from the WebSocket conn.

Does that make sense?

**Comment by undeadindustries** [comment]
It does. I feel like an ass for opening up a question for this. Thanks for you help!

**Comment by elithrar** [comment]
No need to feel like an ass! WebSockets “break” (by design) the HTTP
request - response paradigm and it can be tricky to adopt at first!

Glad we managed to figure it out.
