### ISSUE TITLE
FilesystemStore : Is there a reaper?

### ISSUE THREAD

**Issue by SachinVarghese** [gorilla/sessions#214]
Is there a reaper for the FilesystemStore that deletes stale sessions at a regular interval?
An example would be `boltstore` reaper created [here](https://github.com/yosssi/boltstore/tree/master/reaper). Is this really necessary?

**Comment by elithrar** [comment]
There is not a "reaper" process to clean up old sessions.

* By default, `FilesystemStore` uses `os.TempDir()`, which is (only) cleaned up at mount (or boot) in most Linux distro
* For custom paths, nothing happens.

I'd nearly always recommend Bolt or Redis over FilesystemStore in general - we should probably reference those stores more clearly.
