### ISSUE TITLE
Old cookies can still be used after a new cookie is generated by the call to `Save` 

### ISSUE THREAD

**Issue by hkhere** [gorilla/sessions#216]
So if you change some session values and then call `session.Save()`,  that will generate a new cookie value and the server will add a `set-cookie` header with this new cookie value. However the old cookie values generated before can still be used (they are still valid).  

Is this behaviour intended?

**Comment by elithrar** [comment]
Yes - if you save the cookie as the same name, valid clients won’t send
both.

It is however valid for the old cookie to continue to be usable as it was
signed by the same key, and as long as it hasn’t expired, it will be
accepted.

This would only be a problem if valid clients sent both and you had the old
values, but that should not happen.

**Comment by hkhere** [comment]
am curious why bother generating a new cookie value while the validity of the old ones persist

**Comment by elithrar** [comment]
For the same cookie name + domain + path, a browser client won’t retain the
“old” cookie - it will be overwritten.

If a user were to extract a cookie and replay it on their own, it remains
valid as it: a) is valid until expiry and b) was signed by the same valid
signing key.

Server side stores (like Redis) allow you to delete the cookie values from
the server for the given cookie ID.

What might help is explaining why this is concerning to you - this is
normal behavior for cookies, given that they are ultimately client
controlled. If you sign them, you are allowing them to be valid for as long
as your signed data indicates.

**Comment by hkhere** [comment]
Thanks for the explanation.

Just figured out how to make redis clear a session when a user signs out. My worries about  old cookies is unneccessary at all.

**Comment by huxulm** [comment]
Hi, @elithrar 
I'm curious why instead of just rolling the cookie's expire time, the cookie's value is updated at the same time.

See here:
[express-session](https://github.com/expressjs/session#rolling)
