### ISSUE TITLE
How to logout another user?

### ISSUE THREAD

**Issue by problama** [gorilla/sessions#217]
**Describe the problem you're having**
 
I'd like to be able to find and invalidate a user's session from the store. The use case is when a moderator wants to kick an abusive user out immediately.
…

**Versions**
go version go1.13.6 linux/amd64

> package version: run `git rev-parse HEAD` inside the repo
15ff3511704639ab26f7843f780c015f4bf49565
…

**"Show me the code!"**
```
package session

import (
	"log"
	"net/http"
	"github.com/gorilla/sessions"
	redisStore "gopkg.in/boj/redistore.v1"
)
 
var Store *redisStore.RediStore
var Name string
var err error

type Session struct {
	Options   sessions.Options `json:"Options"`   
	Name      string           `json:"Name"`      
	SecretKey string           `json:"SecretKey"`  
}

func Configure(s Session) {
	Store, err = redisStore.NewRediStore(10, "tcp", ":6379", "", []byte(s.SecretKey))
	if err != nil {
		log.Fatal("error getting redis store : ", err)
	}
	Store.Options = &s.Options
	Name = s.Name
}
 
func Instance(r *http.Request) *sessions.Session {
	session, _ := Store.Get(r, Name)
	return session
}
 
func Empty(sess *sessions.Session) {
	for k := range sess.Values {
		delete(sess.Values, k)
	}
}
```

So what I want to acheive is something like this:

```
func InstanceUser(UserID int) *sessions.Session {
	session, _ := Store.GetUser(UserID)
	return session
}

```
So that I can be able empty it.

**Comment by elithrar** [comment]
You would need to store an association of user <-> session ID in your backing store, or (better) in your user database. 

e.g. an array of "current sessions" that the user themselves can invalidate, which will delete the matching key from Redis, and that an admin can invalidate on their behalf.
