### ISSUE TITLE
[question] is securecookie required to use this package

### ISSUE THREAD

**Issue by EricDatis** [gorilla/sessions#220]
I get this error when using this package
> `securecookie: hash key is not set`

Do this package require me to use securecookie or something is missing here

> Go version: `go version go1.14.5 darwin/amd64`

> package version: 947297c38923a85d18d497ad4cadfa23688ed3d4

I follow simple use case from example (Saving a value to a session)
```
var store = sessions.NewCookieStore([]byte(os.Getenv("SESSION_KEY")))

func createToken(userid int, w http.ResponseWriter, r *http.Request) error {
        // Generate access token
        session, err := store.Get(r, "auth")
	if err != nil {
		return err
	}
	session.Values[userid] = accToken
	err = session.Save(r, w)
	if err != nil {
		return err
	}
}
```

**Comment by elithrar** [comment]
The `sessions` package uses `securecookie` underneath. You don't need to import it yourself. 

I suspect the value of `os.Getenv("SESSION_KEY")` is empty though. You should whether it is valid at program startup.

**Comment by EricDatis** [comment]
thank for reply! Is there any format that I have to follow for the session key?

**Comment by elithrar** [comment]
Per https://godoc.org/github.com/gorilla/sessions#NewCookieStore

> It is recommended to use an authentication key with 32 or 64 bytes.

Hope that helps!
