### ISSUE TITLE
gorillatoolkit.org is down

### ISSUE THREAD

**Issue by stevesobol** [gorilla/sessions#221]
Visiting any page on that site, I see this message:

`Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.`

**Comment by elithrar** [comment]
We are working to fix this.

**Comment by thorstenkloehn** [comment]
You can’t use the Go packages or you can because they are too old.

**Comment by emmaly** [comment]
I propose closing this issue and redirecting to https://github.com/gorilla/site/issues/13 on this issue.
