### ISSUE TITLE
Gorilla Sessions Examples

### ISSUE THREAD

**Issue by dwrz** [gorilla/sessions#222]
**Is your feature request related to a problem? Please describe.**

The README states:

`More examples are available on the Gorilla website.`

And includes a link to the following: https://www.gorillatoolkit.org/pkg/sessions

That link now redirects to: https://github.com/gorilla/.

**Describe the solution you'd like**

Any chance you can make the examples available in the repo?

**Describe alternatives you've considered**

I'll see if I can use the internet archive in the meantime.

**Comment by elithrar** [comment]
See
https://pkg.go.dev/github.com/gorilla/sessions?tab=doc - which is linked
from the README.

The examples are all in godoc format.

**Comment by dwrz** [comment]
Cheers, thank you!

**Comment by blitzd** [comment]
@elithrar Any chance of updating the README to point to `https://pkg.go.dev/github.com/gorilla/sessions?tab=doc` ? It currently points to `https://www.gorillatoolkit.org/pkg/sessions`, which redirects back to the page with the link (i.e., circular).

I had been searching for examples, but had given up - only found them after reading closed issues.

**Comment by blitzd** [comment]
@elithrar This also looks to be an issue in the schema package with the more examples link, and the handlers package with the more handlers link - they all link to the Gorilla website, which links back to the respective repos. They should probably link to the godoc.
