### ISSUE TITLE
[bug] session.ID

### ISSUE THREAD

**Issue by Vitucho** [gorilla/sessions#224]
**Describe the bug**
 using a `sessions.CookieStore` the session's field ID remains empty ("") for each client
 Original description [here](https://stackoverflow.com/questions/63470100/golang-missing-web-client-gorilla-session-id)

**Versions**
 Go version: go version go1.13.12 linux/amd64
 package version: 947297c38923a85d18d497ad4cadfa23688ed3d4

**Steps to Reproduce**
Start web server, register a web client session and try to print his assigned ID.

**Expected behavior**
 To have a session ID value different than empty.

**Code Snippets**

Start a server and use a client to request the resource located at the root "/" 
The code is the server.
You may user any browser as a client or any other program as a client as long it knows how to handle cookies.

```

package main

import (
    "fmt"
    "net/http"

    "github.com/gorilla/sessions"
)

var (
    key   = []byte("me-gusta-el-mate")
    store = sessions.NewCookieStore(key)
)

func webClientSessionId(w http.ResponseWriter, r *http.Request) {
    session, _ := store.Get(r, "cookie-name")
    session.Save(r, w)
    if session.IsNew {
        fmt.Fprintln(w, "The web client session has been created and his ID value is "+session.ID)
    } else {
        fmt.Fprintln(w, "The web client session already exists and his ID value is "+session.ID)
    }

}

func main() {
    http.HandleFunc("/", webClientSessionId)

    http.ListenAndServe(":8080", nil)
}

```

**Personal words**

Thanks for all the work you have been doing.

**Comment by elithrar** [comment]
`IsNew` isn't set when you save a session. 

Can you share what your intent is / what problem you are trying to solve?

**Comment by Vitucho** [comment]
**the problem is that session.ID is empty,** IsNew is not the object of the issue

**Comment by elithrar** [comment]
Sorry, I meant ID. 

Can you explain what you are trying to solve, first?

**Comment by Vitucho** [comment]
@elithrar the bug is the bug, what i 'm doing is what i'm doing beign a client of your library. These are two different things, shall we agree on that, ¿right?. Your question is based on my code, and i'm putting focus on your code. 

- Your code: The bug is an empty value on the session's ID field where.. ¿it is supossed to be not empty? 
- My code: i want to have an session' ID not empty so i could that ID where i want to use it.

**Comment by elithrar** [comment]
The CookieStore does not set the `Session.ID` value, because in a cookie context there isn't an ID. 

Stores that use other backing data - like the file system or Redis - do store an ID, as that's used to look up the actual session data.

**Comment by Vitucho** [comment]
thanks @elithrar i guess that could be very useful to clarifiy for users. Never the less, behind the curtains how dificult is to assign an id something that you are already tracking. If not the method [store.Get(r, "cookie-name")](url) won't ever get the session for the same web client behind the reques. I know that would be a feature request if you never made it.

In [my post of stackoverflow](https://stackoverflow.com/questions/63470100/golang-missing-web-client-gorilla-session-id) (referenced on the original description of this bug) i stated that my intention is to use that ID in order to track web clients.

**Comment by elithrar** [comment]
There isn't an ID, and to generate one, we would need to use up the limited space in the cookie value (reducing what you can store). 

If you want an ID, I would generate one in your authenticated cookie data and use that.

**Comment by Vitucho** [comment]
@elithrar, as a design, you may hide the ID field if is not intented to be use by any client or is not intented to have actually a meaning.

**Comment by elithrar** [comment]
It can't be selectively hidden.

I am not the original designer. It would probably be better off as a method that returns `(string, bool)` to indicate whether an ID should exist or not, but that would be a breaking change.

Happy to accept a documentation PR on the `ID` field.

**Comment by Vitucho** [comment]
@elithrar can agree more with you!! 
Anyway, thanks again and please thanks to all you guys doing the work mantaining this nice library! 

Keep up the good work!
