### ISSUE TITLE
[bug] gorillatoolkit.org/pkg/sessions - 500 Internal Server Error

### ISSUE THREAD

**Issue by s2qts** [gorilla/sessions#226]
There's some issue with https://www.gorillatoolkit.org/pkg/sessions. It returns `500 Internal Server Error` for a couple of days already.

Could you check, please?

**Comment by elithrar** [comment]
See gorilla/site/#17 - the package documentation may be down for a while. 

See https://godoc.org/github.com/gorilla/sessions - linked from the README - for package documentation.
