### ISSUE TITLE
[question] I do not want securecookies while developing.

### ISSUE THREAD

**Issue by snowdream** [gorilla/sessions#227]
I do not want securecookies while developing.

I want to check whether my session is correct in the redis.

but now ,They are all secret.

How can i do that?

**Comment by elithrar** [comment]
Can you share your code? Are you choosing to encrypt the cookie values?

**Comment by snowdream** [comment]
```bash
package middlewares

import (
	"github.com/gin-contrib/sessions"
	"github.com/gin-contrib/sessions/redis"
	"github.com/gin-gonic/gin"
)

var store redis.Store

func init() {
	// store, _ = redis.NewStore(10, "tcp", "127.0.0.1:8631", "&uaRXq*tgZYRsg{Rt6&", []byte("secret"))
	store, _ = redis.NewStore(10, "tcp", "127.0.0.1:6379", "", []byte("secret"))
	store.Options(sessions.Options{
		MaxAge: 3600,
		Secure: false,
		// Secure:   true,
		HttpOnly: true})
}

// Sessions Sessions
func Sessions() gin.HandlerFunc {
	return sessions.Sessions("gsessionid", store)
}

```

![image](https://user-images.githubusercontent.com/737958/92339860-be10b180-f0ea-11ea-8f34-5b26aa337a7a.png)
@elithrar

**Comment by elithrar** [comment]
That's not encrypted - it's just the raw bytes of the encoded session - in Go's Gob format. 

- Use the JSON Serializer if you need to view the data directly in Redis itself - https://pkg.go.dev/github.com/boj/redistore?tab=doc#JSONSerializer
- alternatively, output the data from Go itself, which has the decoded session

**Comment by snowdream** [comment]
When i use JSONSerializer

I can write the session in the redis with plain text.

but when i get the session ,and convert it to golang module.
"sms = _smssession.(models.Sms)"

```bash

	session := sessions.Default(c)
	_smssession := session.Get("sms")

	if _smssession != nil {

		sms = _smssession.(models.Sms)

		if sms.Count > 10 {
			c.JSON(200, ghttp.JSONResponseFailed("验证码请求失败", "请求次数超过限制，请明天继续尝试。"))
			return
		}

		sms.Code = generator.RandStringBytesMaskImprSrc(6)
		sms.Count = sms.Count + 1
	} else {
		sms = models.Sms{}
		sms.Count = 1
		sms.Code = generator.RandStringBytesMaskImprSrc(6)
	}
```
I get error as follows:

```
interface conversion: interface {} is map[string]interface {}, not models.SafeUser
```

**Comment by elithrar** [comment]
You can't type-cast the `map[string]interface{}` to your type - you will need to define a method that takes the session and outputs your type. 

JSON is a general-purpose serialization format that doesn't know anything about Go types. Gob is specific to Go, and does carry type information, but isn't designed to be human-readable in its encoded form. 

You will have to pick one, and/or write code to fill the gap.

**Comment by snowdream** [comment]
ok，Thank You.
