### ISSUE TITLE
gorillatoolkit.org is down ?

### ISSUE THREAD

**Issue by bokunodev** [gorilla/sessions#228]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

i click a link in readme [this link](https://www.gorillatoolkit.org/pkg/sessions)

…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…
![tmp](https://user-images.githubusercontent.com/54968427/92639388-e9bbb380-f305-11ea-89ae-b1c98bb396bd.png)

**Comment by elithrar** [comment]
See gorilla/sites for an existing issue.

**Comment by geekbozu** [comment]
Will the example and documentation on this ever be getting uploaded else where? Or are we just to use archive.org now?

**Comment by unternet** [comment]
I also am looking for the documentation. Is it available in archive.org? Ill use that instead if that's all that is available.

**Comment by elithrar** [comment]
There is extensive documentation at
https://pkg.go.dev/github.com/gorilla/sessions?utm_source=godoc - the
original site was generated from the godoc.
