### ISSUE TITLE
Why are Options stored on each session record instead of the session store?

### ISSUE THREAD

**Issue by Xeoncross** [gorilla/sessions#233]
Why are Options stored on each [session record](https://github.com/gorilla/sessions/blob/master/sessions.go#L37) instead of the session store? 

Because of this design choice, it seems it's normal practice to work around this by setting the options once on the Store [and just copying them to each session record](https://github.com/gorilla/sessions/blob/9cb0b0a3e38d07f41143f03013eaf0a3243fb474/store.go#L87-L88). Given this pattern, it seems like they should never have been required on the session record to begin with.

How many apps have unique cookie options for a single session, but not others? Why is this design in place?

The only reason I found (I could be missing something) is that we are using the whole Options object as a dual-use struct to [delete the HTTP cookie when needed](https://github.com/gorilla/sessions/blob/master/store.go#L114).

However, this seems so unnecessary [the sample stores don't even bother to save the options when storing the session](https://github.com/gorilla/sessions/blob/master/store.go#L256).

**Comment by elithrar** [comment]
Well before my time, but it would be a breaking change.

One benefit to this approach is that it allows you to expire (by setting
MaxAge: -1) sessions - say, when you want to log a user out, or otherwise
mutate a user session directly.

**Comment by Xeoncross** [comment]
Yes, I outlined that approach as a possible reason, I'm just not sure why that would be used as it seems like bad practice to change session's duration individually (along with bothering to store these unique durations). That would lead to a testing nightmare and the purpose of logging accounts in/out is better served without setting lifespans unique to each session cookie.

I assume the original author had a specific use-case in mind, but perhaps it was just convenience for setting the cookie options.

**Comment by elithrar** [comment]
I think you might be overstating the “testing nightmare” part :)

I do think it’s a legitimate use-case to expire sessions; or set a session
cookie that only lives for that browser session based on user input
(“remember me”).

Regardless, the original motivation was lost to the annals of time - this
package is many years old, especially compared to most Go packages.

**Comment by Xeoncross** [comment]
> I do think it’s a legitimate use-case to expire sessions; or set a session
cookie that only lives for that browser session based on user input
(“remember me”).

I agree they are legitimate needs, but those are usually handled in a different way than setting different session cookie timestamps for each user. Expiring session cookies can be done universally with a single Max-Age set to 0 (or negative) and doesn't need to be tracked in all  fifty thousand user sessions instances. Likewise, "remember me" functionality is generally handled by a separate cookie, not a parameter stored in the users current session. In fact, sessions are usually stored server side and culled after X time periods regardless of what the client cookie says.
