### ISSUE TITLE
[question] How to set multiple cookies in one request?

### ISSUE THREAD

**Issue by iammarkps** [gorilla/sessions#234]
**Describe the problem you're having**
I want to set multiple cookies, in one request. But it don't seem to have a method to do so.
Two Cookies is
1. Session cookie itself
2. Cookie that only tell if user is logged in

**Versions**

Go version: `go version go1.15.5 linux/amd64`
package version: `github.com/gorilla/sessions v1.2.0`

**"Show me the code!"**
```go
	sess, _ := session.Get("Session", c)
	sess.Options = &sessions.Options{
		Path:     "/",
		MaxAge:   86400 * 7,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
	}

	sess.Values["user"] = User.StudentID
	sess.Values["timestamp"] = time.Now()

	err := sess.Save(c.Request(), c.Response())
```

**Comment by elithrar** [comment]
Replace:

sess, _ := session.Get("Session", c)


... with:

sessCookie, err := session.Get("session", c)

loginState, err := session.Get("login", c)
