### ISSUE TITLE
I'm sorry, delete this issue please

### ISSUE THREAD

**Issue by robinjulien** [gorilla/sessions#236]

**Comment by elithrar** [comment]
Cookies with the “Secure” attribute are only sent back to the server when
the connection is HTTPS. Are you testing on a local dev server without
HTTPS?

Or are you saying it is not “set” - the Set-Cookie header will still
include the cookie, but the browser will not store it.

**Comment by robinjulien** [comment]
Yes I was until I realized it. I'm sorry for opening an issue for that.
