### ISSUE TITLE
[question] Is there a way to store session data in file system and not in cookie

### ISSUE THREAD

**Issue by asaqib27** [gorilla/sessions#247]
I have tried both CookieStore and FilesystemStore. They seem to work in a very similar way both store data in a cookie the only difference I found is FilesystemStore also store data in the filesystem along with a cookie.

Is there a way to implement it in a standard way where we just store session ID in cookie and store session data in filesystem with same id.

**Comment by elithrar** [comment]
The FileSystemStore only saves the session name and ID to the cookie, not the full session data: https://github.com/gorilla/sessions/blob/master/store.go#L239
