### ISSUE TITLE
redigo: get on closed pool

### ISSUE THREAD

**Issue by xujb977644703** [gorilla/sessions#258]
// Add a value
	session.Values["foo"] = "bar"

	// Save session
	if err = sessions.Save(req, w); err != nil {
		log.Fatal("failed saving session: ", err)
	}

when the "bar" is interface{},the session.save is err,why?

**Comment by xujb977644703** [comment]
``

**Comment by elithrar** [comment]
Don’t ignore the error here:

store, _ = redistore.NewRediStore(c.Redis.Db, "tcp", c.Redis.Addr, "",
[]byte("secret-keyS"))

**Comment by bharat-rajani** [comment]
@xujb977644703 I am not getting the error when using interface. Can you provide some code with which we can reproduce the error you would be facing?

```
func MyHandler(w http.ResponseWriter, r *http.Request) {
	session, _ := store.Get(r, "session-name")
	var a interface{}
	session.Values["foo"] = a
	session.Values[42] = 43
	err := session.Save(r, w)
	if err != nil {
		log.Default().Println(err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
}
```

**Comment by jaitaiwan** [comment]
This issue appears to be specific to redis; I'm going to close this out unless we can come up with a test or example which proves a bug. Thanks!
