### ISSUE TITLE
[FEATURE] <Adding support for Partitioned attribute for 3rd Party Cookie deprecation>

### ISSUE THREAD

**Issue by kashishbehl** [gorilla/sessions#272]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

Chrome will be disabling [3rd Party Cookie](https://developers.google.com/privacy-sandbox/3pcd/prepare/prepare-for-phaseout) support by the end of June 2024. As a solution chrome has added support for creating cookies with independent partitioned state called [CHIPS](https://developers.google.com/privacy-sandbox/3pcd/chips).
This will be achieved by adding `Partitioned` attribute in cookies to allow cookie to be partitioned to the website where it is set.

### Describe the solution that you would like.

We need to add support for a new cookie attirbute named `Partitioned`.

**Comment by jaitaiwan** [comment]
Thanks for bringing this to our attention. I'll have to take a look at how to fix this.

**Comment by jaitaiwan** [comment]
Support added in v1.4.0
