### ISSUE TITLE
[Bug] unknown field 'Partitioned' in struct literal of type http.Cookie

### ISSUE THREAD

**Issue by kramesh2005new** [gorilla/sessions#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting following issue while get this package and building because of filed 'Partitioned' implementation

![Screenshot from 2024-05-08 14-53-57](https://github.com/gorilla/sessions/assets/15984533/9ed2e4ff-fc84-4e1b-967d-13c0c0c2c44b)

### Expected Behavior

The issue unknown field 'Partitioned' in struct literal of type http.Cookie should not happen while get this package and building. 

### Steps To Reproduce

Get the package using following command 

go get github.com/gorilla/sessions

**Comment by jaitaiwan** [comment]
Thanks for the report, I'll have to take a look at how best to sort this.

**Comment by jaitaiwan** [comment]
Fixed in v1.3.0. Main branch is to be considered unstable till go 1.23
