### ISSUE TITLE
invalid key size 

### ISSUE THREAD

**Issue by kostonstyle** [gorilla/sessions#32]
When I create new cookie store and do like:
```go
var store = sessions.NewCookieStore(securecookie.GenerateRandomKey(1), securecookie.GenerateRandomKey(2))
```
I've got the the error message 
`crypto/aes: invalid key size 2 `

Why what do I wrong?

**Comment by steakejjs** [comment]
Try this instead
```
var store = sessions.NewCookieStore(securecookie.GenerateRandomKey(32), securecookie.GenerateRandomKey(32))
```

**Comment by elithrar** [comment]
Note that the docs (which are really good!) cover this: http://www.gorillatoolkit.org/pkg/sessions#NewCookieStore

> It is recommended to use an authentication key with 32 or 64 bytes. The encryption key, if set, must be either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256 modes.

If you do use the above method and restart your application, previous sessions will not be able to be used. You can also generate a couple of keys and save them in a configuration file (never in your source code) or environment. Use `os.Getenv` to retrieve via the latter method.

At the command-line:

```
$ openssl rand -base64 32 
```

... will generate a key of the correct length.
