### ISSUE TITLE
Improve CookieStore.Save's network efficiency with sliding window cookie refresh

### ISSUE THREAD

**Issue by fluffysquirrels** [gorilla/sessions#38]
The [current implementation of CookieStore.Save](https://github.com/gorilla/sessions/blob/3cb09c3e9541606b194a45b02b85176b6e4635f4/store.go#L100-L110) always calls http.SetCookie, hence always sending writing a "Set-Cookie" HTTP response header even if no data has changed.

This could be made more efficient. How about making it possible to only write a "Set-Cookie" header when the CookieStore's data has changed or the session cookie is close to expiry? This is the default strategy used by [.NET's FormsAuthentication](https://msdn.microsoft.com/en-us/library/system.web.security.formsauthentication.slidingexpiration(v=vs.110).aspx).

**Comment by kisielk** [comment]
Sure, that could be an option on CookieStore as long as we keep the current behaviour as the default. Would you be interested in writing up a PR for this?

**Comment by fluffysquirrels** [comment]
Yes, I'd love to work on a PR for this, but I'm busy working on an MVP for an app right now. Hopefully I will have time after that to work on this and https://github.com/gorilla/mux/issues/13.

**Comment by kisielk** [comment]
Great, thanks. I don't have a lot of time to work on adding that right now and you seem to have a better idea of what's needed anyway.

**Comment by elithrar** [comment]
I'm going to close this one out for now unless there's interest in adding it. In order to check that a cookie hasn't changed you would still need to decode (importantly: authenticating it) the incoming cookie before knowing whether to write changes out.
