### ISSUE TITLE
Store.Save should return error if ResponseWriter.Write has been called

### ISSUE THREAD

**Issue by rcadena** [gorilla/sessions#39]
Not sure if this is something to be handled at the Store.Save level or if people should just exercise caution, but, what about returning an error on Save if the ResponseWriter.Write has been called? 

See relevant line here: https://github.com/gorilla/sessions/blob/master/store.go#L101

Here's one example of someone who ran into a problem because they were unaware that they should call Save before writing to the response.

http://stackoverflow.com/questions/21865681/sessions-variables-in-golang-not-saved-while-using-gorilla-sessions

Relevant godoc here: http://golang.org/src/net/http/server.go?s=1500:2376#L70

I'm not sure what the correct check should be though.  

Happy to work on a PR if you think this is a worthwhile enhancement.

**Comment by elithrar** [comment]
The overarching problem is that doing anything after writing to the
ResponseWriter is "fraught with peril" (unless it's logging internally).

I suppose if you were to check you would see if w.Header() returns a
non-empty result, but even then - the best you can do is generate an
internal error. Once you've written to the ResponseWriter, session.Save
might return an error but you can't turn around and send a HTTP 500 as it's
already too late.

**Comment by kisielk** [comment]
I agree with @elithrar, it's definitely a gotcha but I think if there were a sensible way of detecting and dealing with it then the http package would already make updating the header after writing an error. Most of the time people wouldn't log an error from session.Save on the server side anyway because in the majority of cases it would be from a connection problem to the client which may happen often enough that you'd just be spamming your logs.

Probably improving the documentation is the best answer.

**Comment by rcadena** [comment]
Thanks for the feedback. Yeah, I agree. After thinking about it, it also seems like it'd be the wrong kind of error for store to return; the problem was with setting the header not with storing the cookie. 

Updating the doc is probably a good idea because it tripped me up to follow the small example for AddFlash.

**Comment by kisielk** [comment]
Yeah actually it looks like the flashes example is simply wrong because it saves after a Fprintf to the ResponseWriter. The other examples don't have any writes at all. I think if we tweaked the examples and added a note somewhere it would make things a lot clearer.
