### ISSUE TITLE
Filesystem store question

### ISSUE THREAD

**Issue by ciarand** [gorilla/sessions#41]
[Does this leak file descriptors?](https://github.com/gorilla/sessions/blob/master/store.go#L221-L229) (most comments mine)

```go
// save writes encoded session.Values to a file.
func (s *FilesystemStore) save(session *Session) error {
	// - snip -
	fp, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	// Now we have an open file
	if _, err = fp.Write([]byte(encoded)); err != nil {
		return err // <----------------- Fail a write and return without Closing
	}
	fp.Close() // Safely close the file
	return nil
}
```

**Comment by kisielk** [comment]
Hm yes, but temporarily until fp is garbage collected and the finalizer closes it. It should be fixed to use a defer though.

**Comment by ciarand** [comment]
Ok, thank you for clarifying :sparkles:

**Comment by kisielk** [comment]
Thanks for pointing it out :) It shouldn't have been a problem in practice since it's unlikely you'd get an error, and even if you did the filehandle would eventually be collected. But always better to do things right :+1:
