### ISSUE TITLE
Why not use "comma ok" idiom to ensure not crash with a run-time error 

### ISSUE THREAD

**Issue by bsnwong** [gorilla/sessions#49]
Hi,
When I use this package with the functions `Flashes` defined inside the file `sessions/sessions.go` on [line 69](https://github.com/gorilla/sessions/blob/master/sessions.go#L69), I got a panic like this: `interface conversion: interface is string, not []interface {}`, and I found this could be solved by using "comma ok" idiom such as `flashes, ok = v.([]interface{})`, which is also mentioned in the [document](https://golang.org/doc/effective_go.html#interface_conversions) of official site

**Comment by kisielk** [comment]
Can you provide some example code that causes the problem? The only thing that should be setting flashes is the `AddFlash` function which should guarantee the value is an []interface{}.

**Comment by bsnwong** [comment]
@kisielk

**Comment by bsnwong** [comment]
@kisielk 
Sorry about my question, I did not set the value by using the `AddFlash` function
By the way, so the problem will occur once we do not set the value by using `AddFlash`  function, which ensure the value should be an `[]interface{}`?
ps: sorry about my description : -(

**Comment by kisielk** [comment]
Yes, the code assumes the flashes are added via `AddFlash`. If you're doing it manually, you need to ensure the value you set is of type `[]interface{}`
