### ISSUE TITLE
Filesystem store without using cookies?

### ISSUE THREAD

**Issue by stapelberg** [gorilla/sessions#5]
I am developing a web application which is used by paranoid people who turn off cookies by default and things like that.

Given that the cookie only stores a session identifier, I could just pass that identifier as a hidden field in my form. However, the current API of FilesystemStore does not allow that, it always wants to set/get a cookie.

Aside from setting the cookies before calling the API and deleting the cookie which is returned, would you be open to adding a way to use the FilesystemStore without cookies?

**Comment by elithrar** [comment]
Closing this for (some future) v2.
