### ISSUE TITLE
question about generated session.ID

### ISSUE THREAD

**Issue by nickpoorman** [gorilla/sessions#54]
Maybe I'm missing something but this: https://github.com/gorilla/sessions/blob/master/store.go#L215 seems to generate a random session ID. I would like my user sessiond IDs to be something like: `hash(username + secretSalt + timestamp)` to remove the possibility of a user getting another user's session ID.

Can someone clarify this for me, or is there a way I should be setting the ID ahead of time so this doesn't get set?

**Comment by elithrar** [comment]
The generated ID is 2^256 bits - effectively improbable to collide even if
you are generating 10 million IDs *per second*. A scheme that hashed the
username+timestamp wouldn't offer better guarantees and would be more
brittle.

Look up the birthday paradox as it relates to cryptography.

**Comment by nickpoorman** [comment]
Ok thank you.

**Comment by Tom29** [comment]
Hi, why after i print out session.ID, it's an empty string? What's difference between `store` and `save`?

**Comment by elithrar** [comment]
@Tom29 Can you show your code?

The ID is generated by a Store—specifically stores that use a combination of cookies + backend—so that it can lookup the session given an ID.

The CookieStore has no backend (everything is stored in an authenticated cookie) and thus does not need session IDs.

**Comment by elithrar** [comment]
Are you using the FilesystemStore or the CookieStore?

If you are using the latter there is no session ID (it’s not required).

Please share a minimal runnable example if my assumption here is wrong.
