### ISSUE TITLE
question about "wrap your handlers with context.ClearHandler as or else you will leak memory"

### ISSUE THREAD

**Issue by vinceyuan** [gorilla/sessions#55]
There is an important note in the doc http://www.gorillatoolkit.org/pkg/sessions 

```
Important Note: If you aren't using gorilla/mux, you need to wrap your handlers with 
context.ClearHandler as or else you will leak memory! An easy way to do this is to 
wrap the top-level mux when calling http.ListenAndServe:

http.ListenAndServe(":8080", context.ClearHandler(http.DefaultServeMux))
```

I checked the code. context.ClearHandler just calls context.Clear which modifies local variables. https://github.com/gorilla/context/blob/master/context.go#L91-L105

Sounds like we don't need to wrap handlers with context.ClearHandler if not using gorilla/mux. Is it correct?

**Comment by elithrar** [comment]
You definitely still need to call `context.ClearHandler` when *not* using gorilla/mux — gorilla/mux does this for you (so it's the exception to the rule).

Take a look at https://github.com/gorilla/sessions/blob/e727cdeb0ad3561b76d753ceeb50d900baf6344e/sessions.go#L107-L133 - which shows where gorilla/context is used on a per-request basis with sessions. If you don't clear the request context you'll eventually end up with a bunch of abandoned `*Registry` items in the context map (leaking memory, effectively).

**Comment by vinceyuan** [comment]
@elithrar You are right. `gorilla/session.GetRegistry()` calls `context.Set`. That's why we need to call `context.Clear`. Many thanks!

**Comment by moar55** [comment]
I am using beego but I want to use gorilla's session. Is there a way to add this in the beego code?

**Comment by elithrar** [comment]
Beego is pretty tightly integrated, and I’m not familiar with the code.

What have you tried so far?

**Comment by moar55** [comment]
I tried digging into beego server source code. The problem is they aren't using the net/http module only the net module and serving it their own way, so I am unsure how to add such mux.
