### ISSUE TITLE
I made a naive mistake to set session key with a struct/point

### ISSUE THREAD

**Issue by cclient** [gorilla/sessions#58]
then the sessions not work

notice others develpers

byte the way 

i suggest that  while set a no serialized value to session return an error or add value type check

**Comment by elithrar** [comment]
Can you show your code for this? (i.e. the mistake you made)

**Comment by cclient** [comment]
just because type issue
type Account struct {
	Name string
}
1: work well
session, _ := tool.GetWebSession(r)
session.Values["hello"] = "word"
session.Save(r, w)

2:not work
session, _ := tool.GetWebSession(r)
session.Values["hello"] = "word"
session.Values["struct"] = Account{}
session.Save(r, w)

3:serializabled work well
session, _ := tool.GetWebSession(r)
session.Values["hello"] = "word"
jinfo, _ := json.Marshal(Account{})
session.Values["struct"] =jinfo
session.Save(r, w)

**Comment by elithrar** [comment]
Note that whether an object is a value or a pointer shouldn't matter - you can store either `Account{}` or `&Account{}` in a session and retrieve it. Here's a runnable example demonstrating it:

```go
package main

import (
	"encoding/gob"
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/sessions"
)

var store = sessions.NewCookieStore([]byte("key"))

type Project struct {
	ID string
}

func PutHandler(w http.ResponseWriter, r *http.Request) {
	sess, err := store.Get(r, "test_sess")
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}

	project := Project{"8138ahd913"}
	sess.Values["proj"] = project
	err = sess.Save(r, w)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}

	fmt.Fprintf(w, "Value saved")
}

func GetHandler(w http.ResponseWriter, r *http.Request) {
	sess, err := store.Get(r, "test_sess")
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}

	fmt.Fprintf(w, "%#v", sess.Values)
}

func main() {
	gob.Register(Project{})

	http.HandleFunc("/puthandler", PutHandler)
	http.HandleFunc("/gethandler", GetHandler)

	log.Fatal(http.ListenAndServe(":8000", nil))
}
```

Like any custom type you need to call `gob.Register` to allow encoding/gob to serialize it (which is what sessions uses underneath, by default).

If I've misinterpreted your issue, post up an example I can run that demonstrates it. Going to close this for now!
