### ISSUE TITLE
Session expiration func

### ISSUE THREAD

**Issue by dubiousdavid** [gorilla/sessions#6]
It would be nice is there was an expire func that in the case of cookie sessions set the cookie lifetime to a time in the past.  Let me know what you think.

**Comment by elithrar** [comment]
Closing this for (some future) v2.

**Comment by olliephillips** [comment]
Would be nice to see some kind of 'delete', 'destroy' method, however implemented.

**Comment by skyguy126** [comment]
I agree with @olliephillips

**Comment by elithrar** [comment]
I'm going to lock this for now as there's not much we can do: we can't change the public `Store` interface.
