### ISSUE TITLE
How to clear another user session ?

### ISSUE THREAD

**Issue by tbruyelle** [gorilla/sessions#60]
From an admin interface in a website, I can disable a user, and in that case, I would like also to remove his current session, in order to disconnect him instantly.

From what I see I can only access the session with `http.Request`, but in that case I don't want to access my session but the one from another user. Can I do that ?

(I know I can also check the database each time I get a session to see if the user is disabled, but I wonder if it's possible without a db access)

**Comment by elithrar** [comment]
Hi @tbruyelle —

In short: when using the cookies, you can't.

Cookies (in general, beyond this package) are stateless—they may contain an expiry/max. age, but there's no way to forcibly expire them without maintaining some state somewhere. Typically, this would be in a database, and you would look up that user on login (or every request) based on a user ID stored in the cookie.

The alternative is to use cookies backed by a database, which might be Redis, BoltDB, Postgres, etc. The cookie just stores an ID and that's used on each request to lookup the associated session in the DB. You can then—with an interface to do so—expire sessions based on a session ID <=> user ID mapping. 

Note that this isn't a limitation of this package, just cookies in general. Being able to forcibly expire sessions is one of the advantages of server-side sessions.

**Comment by tbruyelle** [comment]
I understand, thank you for the explanation.
