### ISSUE TITLE
Would the file created by FilesystemStore will be deleted automatically?

### ISSUE THREAD

**Issue by WithGJR** [gorilla/sessions#65]
Same as title.

I found a problem and I want to check if my thought is right.

If I use FilesystemStore and set the expired time for that session, the cookie will be deleted when time is up, but the file created by FilesystemStore will still exist.

Is it will be deleted later ? Or all the session files will not be deleted forever ?

**Comment by elithrar** [comment]
Old, expired sessions are not cleaned up. The FileSystem store is fairly basic. You would need to write some logic that can read expired sessions and delete them.

[boltstore](https://github.com/yosssi/boltstore) (based on BoltDB) is a file-based session store that automatically cleans up expired sessions. I'd recommend using that instead.
