### ISSUE TITLE
Error setting and retrieving session

### ISSUE THREAD

**Issue by pereztr5** [gorilla/sessions#68]
Route: `/login`
When sending a POST it correctly authenticates. It then redirects you to `/team/teamPage`.  
Expected: When going to `/team/teamPage` if you have a valid session then you will end up going to `/teamPage.html`,which is currently blank, if not you will be redirected back to `login.html`

Problem: When successfully logging in I still get redirected back to `/login.html` by the `RequireLogin` function which is not suppose to happen after a successful login.

These are the functions in question:
`func Login`
https://github.com/pereztr5/cyboard/blob/master/cmd/newRoutes.go#L50

`func RequireLogin`
https://github.com/pereztr5/cyboard/blob/master/cmd/middleware.go#L74

`func CheckCreds`
https://github.com/pereztr5/cyboard/blob/master/cmd/webHandler.go#L24

I know I am not saving the sessions correctly because when looking at the header information I do not see any cookies set with the team IDs.

**Comment by elithrar** [comment]
OK, there's a few problems you need to sort out that make it hard for me to run this locally:

* You redirect to static pages like `login.html` but your static routes appear to be commented out? (why not just render a template in-place)
* You handle two HTTP methods in a single handler, which doesn't help with clarity.
* You weren't calling `return` after `http.Redirect(w, r, "/team/teamPage", 302)`, which results in the handler logic continuing and potentially subtle issues (this was probably causing the bad re-direct).
* `Logout` wasn't saving the session after deleting the `id`.
* You were storing the session in the context, which was unnecessary. gorilla/sessions does this itself after the first call to `store.Get` during a request. Just call `sess, err := store.Get(r, "cyboard")` when you need to interact with a session.

I'm about to push a PR to your local branch with some changes. You will have to run them locally to test. Also look at the `TODO` notes I've added for some further fixes you can look at implementing.

**Comment by elithrar** [comment]
See https://github.com/pereztr5/cyboard/pull/2 @pereztr5

**Comment by pereztr5** [comment]
Thanks @elithrar for taking a look and explaining the changes. Also I appreciate the license file! I will test them now.

**Comment by pereztr5** [comment]
Okay the more verbose logging is helping. The error I am getting now is
```
2016/02/21 02:41:00 CheckCreds failed: securecookie: error - caused by: securecookie: error - caused by: gob: type not registered for interface: bson.ObjectId
```
I am registering the `Team` struct which includes the variable `Id` as a bson.Object. Maybe I should save it as a string instead?

**Comment by pereztr5** [comment]
Thank you @elithrar I really appreciate the help!
To answer the first bullet point I am using `negroni` to server the files. What I had did not work.
