### ISSUE TITLE
':' character in session name causes session cookie to not be written

### ISSUE THREAD

**Issue by kliron** [gorilla/sessions#69]
```
session, err := conf.SessionStore.Get(r, "myapp:session")
session.Values["foo"] = "bar"
if err := session.Save(r, w); err != nil {
    freakOut()
}
```

The above code does not produce _any_ errors. The session cookie is never written though. No idea why. Replacing "myapp:session" with "myapp-session" fixes the problem. 

Not sure if this is something specific to gorilla session but as far as I know illegal characters for cookie names include whitespace, comma and semicolon but not colon. It would be nice if Get() would do a sanity check on cookie names and fail with an error in such a case.

**Comment by elithrar** [comment]
Go's `http.SetCookie` does not accept a colon as a valid token: https://github.com/golang/go/blob/39ad0fd0789872f9469167be7fe9578625ff246e/src/net/http/lex.go#L14-L101

I'm open to a pull request that checks this, but because that code in the Go std. lib isn't exported, you would need to copy the whole table over and iterate when calling `Get`.

**Comment by kliron** [comment]
I see. So according to the documentation "Invalid cookies may be silently dropped" https://github.com/golang/go/blob/39ad0fd0789872f9469167be7fe9578625ff246e/src/net/http/cookie.go#L127-L134

I don't really understand why one would make such a choice instead of returning an error from SetCookie() but I'm new to Go and I'm unfamiliar with the std library so there may be some deeper wisdom here I am oblivious to. I'll be back with a pull request.

**Comment by elithrar** [comment]
I agree that http.SetCookie should probably return an error. It was likely
an oversight prior to Go1 and changing it now would be breaking.

Thanks for volunteering to submit a PR on this as well!

**Comment by elithrar** [comment]
Closed via https://github.com/gorilla/sessions/pull/70
