### ISSUE TITLE
Create a new Filesystem backed session if a match can't be found

### ISSUE THREAD

**Issue by gtaylor** [gorilla/sessions#7]
I'm using the Filesystem session store, and emptied my session directory after creating a session to see what would happen. The log message looked like this:

```
2013/01/30 00:42:44 open /Users/gtaylor/Documents/workspace/gopath/src/monweb/sessions/session_5A5RY546OOHJUSK5DEVARK7LFUW2NRLCNMC2V2TS2AVQ4GB22ZBA: no such file or directory
```

Perhaps it would be a good idea to create a new session instead of a hard failure? This appears to currently be an unrecoverable error, since the user has a cookie set with the session ID, but the match always fails.

**Comment by NCSantos** [comment]
Still no way to handle this?

**Comment by elithrar** [comment]
I'm certainly open to any help on this—extremely time constrained.

**Comment by glaslos** [comment]
I ran into the same issue. Thought about it and concluded the current implementation is fine by me. By returning the error I can decide how I want to handle it: Create a new session with the same id? Create a new id? Return an error to the client? What if the client has changed the session id? Someone brute forcing session IDs? IMHO this is a wont-fix.

**Comment by fardok** [comment]
i dont understand: FilesystemStore    save  sessions to the file on client browser or in server directory?

**Comment by glaslos** [comment]
@fardok the session and it's data is stored on the file system server side and on client side the session id in a cookie.

**Comment by TheMangoTrain** [comment]
I have a similar error (using MacOS 10.12.6): 

> remove /var/folders/1c/btjqtfcn1291_65wj5jphtg40000gn/T/session_: no such file or directory

I cleared browser cookies, and error disappeared. Similarily, a fresh other-browser worked fine with the same auth URL. So definitely a cookie thing.

I understand the suggestions OP and glaslos made; Just making a new session ID sounds best. What's the best way to do this? An example func would be appreciated.
