### ISSUE TITLE
sessions.FilesystemStore doesn't implement sessions.Store

### ISSUE THREAD

**Issue by rascalking** [gorilla/sessions#73]
I'm trying to write a piece of middleware that accepts a `sessions.Store` supplied by the application, and I'm getting errors any time I try to pass a `sessions.FilesystemStore`.  This simplified snippet:

```go
package main

import (
    "fmt"
    "github.com/gorilla/sessions"
)

func printStore(store sessions.Store) {
    fmt.Printf("%v", store)
}

func main() {
    // set up FilesystemStore
    fsStore := sessions.NewFilesystemStore("", []byte("some key"))
    fsStore.MaxLength(0)

    // print it
    printStore(*fsStore)
}
```

gets me this output:

```bash
[dab178@bonnerbook src]$ go run foo.go
# command-line-arguments
./foo.go:18: cannot use *fsStore (type sessions.FilesystemStore) as type sessions.Store in argument to printStore:
        sessions.FilesystemStore does not implement sessions.Store (Get method has pointer receiver)
```

I'm new to go, and am more than happy to find out I'm just missing a cast somewhere, but the error message `go run` gives makes me think it's not just me.

**Comment by elithrar** [comment]
Just printStore(fsStore).

sessions.NewFileSystemStore already returns a pointer.

**Comment by rascalking** [comment]
Yeah, I thought I needed to dereference the pointer in order to pass it in, but that did the trick.  My non-simplified problem was in saving a `*sessions.FilesystemStore` in a struct with

**Comment by rascalking** [comment]
In case anyone else who's new to go's type system finds this...the problem was that `sessions.FilesystemStore` *doesn't* implement `sessions.Store`.  But `*sessions.FilesystemStore` does, which is why my explicit dereference triggered that error...`*sessions.FilesystemStore` is a different type from `sessions.FilesystemStore`.
