### ISSUE TITLE
session.Values

### ISSUE THREAD

**Issue by Fruchtgummi** [gorilla/sessions#83]
Hi :)

How cannot store map's in session.Values? 

:)

**Comment by elithrar** [comment]
```
func main() {
	// Register the type so encoding/gob can encode/decode it
	gob.Register(map[string]string{})
	...
```

(Slightly) buried in the docs here: http://www.gorillatoolkit.org/pkg/sessions#overview

**Comment by elithrar** [comment]
Closing for now, but reach out if you still need help.
