### ISSUE TITLE
FastHTTP support?

### ISSUE THREAD

**Issue by painhardcore** [gorilla/sessions#85]
Any thoughts?

**Comment by elithrar** [comment]
sessions does not currently support FastHTTP and there are no plans to do so. I'm open to proposals, but they can't break the current API.

Also note that any application using sessions and databases are unlikely to benefit from FastHTTP as the database will be the bottleneck long before net/http is.

**Comment by painhardcore** [comment]
My point, that application can use use memory to store sessions and sometimes one part of application needs to be fast as FastHTTP and will not use database.
I'm guess that i only one who needs this.

**Comment by elithrar** [comment]
@painhardcore What is the actual use-case? sessions are also gob encoded by default, which will be a bottleneck.

(I'm suggesting that FastHTTP here is a premature optimization if you're designing a session-based, user-facing application. Template rendering or the default encoding/json package also present bottlenecks, but well after tens of thousands of req/s).

**Comment by elithrar** [comment]
Closing for now as there's no intent to support FastHTTP. FastHTTP + user sessions don't make a lot of sense.

**Comment by EtienneBruines** [comment]
I'm just leaving this here for anyone reading this issue:

https://github.com/clevergo/sessions

(Not mine, but might as well use/improve it instead of writing own implementation)

**Comment by knadh** [comment]
@elithrar
> FastHTTP + user sessions don't make a lot of sense.

 Not hinting at re-opening the issue, but this may not necessarily be the case. We've seen significant improvements (latency, requests/sec throughput) simple by switching to fasthttp from net/http in production in cases that involve Redis based sessions on top of pulling and serving sizeable chunks of data from Redis.

@EtienneBruines Thanks!
