### ISSUE TITLE
AppEngine Support

### ISSUE THREAD

**Issue by dsoprea** [gorilla/sessions#88]
What's the status of the Datastore and Memcache support for AppEngine?

This project, at least its documentation, provides instructions:

https://godoc.org/github.com/yanunon/go-tap/gae/code.google.com/p/gorilla/appengine/sessions

However, the Github-redirection link at the top sends the user to the main Gorilla site and it doesn't mention Datastore/Memcache at all.

Plus, when I do a go-get, I get this:

```
package code.google.com/p/gorilla/appengine/context: unable to detect version control system for code.google.com/ path
package code.google.com/p/gorilla/securecookie: unable to detect version control system for code.google.com/ path
package code.google.com/p/gorilla/sessions: unable to detect version control system for code.google.com/ path
```

This is not to mention the worrisome URL of the documentation mentioned above and the corresponding import package mentioned therein. It stinks of obsolescence but I can't fathom why that would be since the rest of your projects seem solid and it was a convenient package to have around.

**Comment by elithrar** [comment]
The packages listed are third party stores; they are not maintained by the
Gorilla maintainers.

https://github.com/hnakamur/gaesessions is another package on the list but
I have not checked it so YMMV.

Otherwise, you would need to consider writing a new store. I would fork the
redistore package (which is of high quality), which would get you most of
the way there.

**Comment by dsoprea** [comment]
Thanks for the pointer. I implemented a cascading session store on top of Memcache and Datastore, and, if desired, the request-context. It's been dogfooded and works great.

https://github.com/dsoprea/goappenginesessioncascade

**Comment by elithrar** [comment]
Nice work! Want to submit a PR for the README? I will remove the old,
unsupported stuff and add yours.

**Comment by dsoprea** [comment]
Thank you, @elithrar. PR submitted.

**Comment by elithrar** [comment]
Thanks @dsoprea! Glad to feature your work.

**Comment by dsoprea** [comment]
Thanks for the advice. I'm still incredulous that there doesn't already
exist a popular AppEngine solution.
