### ISSUE TITLE
Some help-related questions

### ISSUE THREAD

**Issue by hacdias** [gorilla/sessions#91]
Hey!

I'm thinking about using this package for an authentication system using a CookieStore. Since the cookies are encrypted, I was thinking how secure can it be compared to using a database.

I just want to store three values:

```
logged bool
admin bool
id int
```

Is this XSS attack proof?

One more question: the cookie expiration date is defined when it is created in the first time or it is updated every time the user hits the page?

Thanks :smile:

**Comment by hacdias** [comment]
One more question: the 'keyPairs' are used for encryption, right? I was thinking about setting some random at the startup, but if I needed to reset the server, the users would be automatically logged out, right? (I think this is obvious, but I had to ask)

**Comment by elithrar** [comment]
Yes, generating keys on startup invalidates all existing sessions (unless
you happened to save those keys).

XSS and encrypted cookies aren't related: encryption means the end-user
can't see the cookie values (not often useful), but an attacker could still
copy the entire cookie and use it in a replay attack.

Using TLS, preventing mixed content from loading via
Content-Security-Policy headers and setting HttpOnly on the cookie is more
important here.

**Comment by hacdias** [comment]
Hey @elithrar! Thanks for being that fast and for explaining that.

And, what about "One more question: the cookie expiration date is defined when it is created in the first time or it is updated every time the user hits the page?"

**Comment by elithrar** [comment]
Only when you call sessions.Save, which is usually only when created. You
can call it again to reset it (since it just creates a new Set-Cookie
header with the cookie value).

(Saving on creation is more efficient and usually what you want).

**Comment by hacdias** [comment]
Hey! I want the cookie to expire after one hour of inactivity. So, I have to update it every time the user hits the page. Does it sound correct?

**Comment by elithrar** [comment]
Yes, that would be the way to do it.

**Comment by hacdias** [comment]
Thanks for everything!
