### ISSUE TITLE
MaxAge checks against wrong value in Save func

### ISSUE THREAD

**Issue by mziraki** [gorilla/sessions#96]
@pappz @elithrar
in file store.go, line 216:

``` go
func (s *FilesystemStore) Save(r *http.Request, w http.ResponseWriter,
    session *Session) error {
    // Delete if max-age is <= 0
    if session.Options.MaxAge <= 0 { \\ this line
        if err := s.erase(session); err != nil {
            return err
        }
        http.SetCookie(w, NewCookie(session.Name(), "", session.Options))
        return nil
    }
...
```

must be "session.Options.MaxAge < 0" because 0 value means browser expires cookie when you close the browser, but when it is "session.Options.MaxAge <= 0". it removes session file right away and when you want to "Save" session with MaxAge 0 for "until browser is open expiration time", Save function tries to delete file that not exists yet and os.Remove() in erase function returns "remove path\to\tempdir\session_: The system cannot find the file specified." PathError.

**Comment by pappz** [comment]
You are probably right. I will working with session handling in the next couple of week and I will check it.

**Comment by lfkeitel** [comment]
As you could probably tell from my misplaced issue, I'm experiencing the same thing. I was using a MaxAge of 0 and after updating the package my application didn't work. I've made a temporary fix in my copy but this could easily trip up others as well.

**Comment by jimd33463** [comment]
I came across the same issue. So, if this hasn't yet been addressed in a subsequent release, how do I go about updating the code for my project? (new to GitHub)

**Comment by kisielk** [comment]
See #103

**Comment by elithrar** [comment]
Closing; tracking in #103
