### ISSUE TITLE
IsNew is always true when browser uses IP address

### ISSUE THREAD

**Issue by ptman** [gorilla/sessions#98]
I'm always getting new cookies with CookieStore and http://127.0.0.1:8000/
But when fetching http://localhost:8000/ cookies seem to work as intended.

Am I doing something wrong or is this not supported?

**Comment by elithrar** [comment]
Can you share more about how you are configuring the store?

**Comment by ptman** [comment]
Does this help https://play.golang.org/p/rqWwDy6fBz ?

**Comment by elithrar** [comment]
Are you generating a new session key every time you restart the service?

- var store = sessions.NewCookieStore(securecookie.GenerateRandomKey(32))

If so, you will lose the ability to verify previous sessions, which is
unrelated to localhost/127.0.0.1 (perhaps a coincidence)

**Comment by ptman** [comment]
Yes, for this test I am. But the issue I described happens during one execution of the service

**Comment by danhardman** [comment]
I think this may be a browser issue. Cookies are stored against host name I think, are you using chrome? Check out your dev tools and see how the cookie is referenced under the Application tab.

<img width="199" alt="screen shot 2016-10-06 at 16 58 21" src="https://cloud.githubusercontent.com/assets/5691966/19159982/23cf4324-8be6-11e6-89c9-b71bc5904044.png">

**Comment by ptman** [comment]
Thank you very much for pointing me in the right direction. Worked well using Firefox.
